// Code generated by GALA transpiler. DO NOT EDIT.

package logger

import (
	"io"
	"log"
	"os"
)

//line logger.gala:9
var StdOut *log.Logger

//line logger.gala:10
var StdErr *log.Logger

//line logger.gala:12
func Init(logFile io.Writer) {
//line logger.gala:13
	StdOut = log.New(io.MultiWriter(logFile, os.Stdout), "[INFO] ", log.Ldate|log.Ltime|log.Lmsgprefix|log.Llongfile)
//line logger.gala:14
	StdErr = log.New(io.MultiWriter(logFile, os.Stderr), "[ERROR] ", log.Ldate|log.Ltime|log.Lmsgprefix|log.Llongfile)
//line logger.gala:16
	StdOut.Println("######### Server Restarted #########")
}
