services:
  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_BOOTSTRAP_USERNAME:?POSTGRES_BOOTSTRAP_USERNAME is required}
      POSTGRES_PASSWORD: ${POSTGRES_BOOTSTRAP_PASSWORD:?POSTGRES_BOOTSTRAP_PASSWORD is required}
      POSTGRES_DB: ${POSTGRES_DATABASE:?POSTGRES_DATABASE is required}
      POSTGRES_MIGRATOR_USERNAME: ${POSTGRES_MIGRATOR_USERNAME:?POSTGRES_MIGRATOR_USERNAME is required}
      POSTGRES_MIGRATOR_PASSWORD: ${POSTGRES_MIGRATOR_PASSWORD:?POSTGRES_MIGRATOR_PASSWORD is required}
      POSTGRES_APPLICATION_USERNAME: ${POSTGRES_APPLICATION_USERNAME:?POSTGRES_APPLICATION_USERNAME is required}
      POSTGRES_APPLICATION_PASSWORD: ${POSTGRES_APPLICATION_PASSWORD:?POSTGRES_APPLICATION_PASSWORD is required}
      POSTGRES_BACKUP_USERNAME: ${POSTGRES_BACKUP_USERNAME:?POSTGRES_BACKUP_USERNAME is required}
      POSTGRES_BACKUP_PASSWORD: ${POSTGRES_BACKUP_PASSWORD:?POSTGRES_BACKUP_PASSWORD is required}

  postgres-migrate:
    environment:
      POSTGRES_MIGRATOR_URI: ${POSTGRES_MIGRATOR_URI:?POSTGRES_MIGRATOR_URI is required}
      POSTGRES_APPLICATION_USERNAME: ${POSTGRES_APPLICATION_USERNAME:?POSTGRES_APPLICATION_USERNAME is required}

  server:
    environment:
      POSTGRES_APPLICATION_URI: ${POSTGRES_APPLICATION_URI:?POSTGRES_APPLICATION_URI is required}
    networks:
      default: {}
      edge:
        aliases:
          - production-server

volumes:
  frontend_dist:
    name: timeful-production-frontend-dist
    external: true
  postgres_data:
    name: timeful-production-postgres-data

networks:
  edge:
    name: timeful-edge
    external: true
