#!/usr/bin/env bash
# Verify the committed GALA twins in server/.
#
# Usage:
#   server/scripts/gala/verify.sh          # drift detection
#   server/scripts/gala/verify.sh --write  # regenerate the committed twins in place
#
# Prints the compiler provenance recorded in server/GALA_COMPILER, transpiles
# every committed twin with the adopted --stdlib-module, then fails on a
# missing or mismatched provenance record, on a twin the compiler does not
# regenerate byte-identically, on a twin whose generated Go imports the banned
# martianoff/gala runtime, on a `gofmt -l` hit, on an orphaned generated twin,
# or on a failing `go build ./...`.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
SERVER_DIR="$REPO_ROOT/server"
PROVENANCE_FILE="$SERVER_DIR/GALA_COMPILER"
GENERATED_HEADER="// Code generated by GALA transpiler. DO NOT EDIT."
STDLIB_MODULE="go.gala.fyi/stdlib"
MODE="${1:-check}"

if [ "$MODE" != "check" ] && [ "$MODE" != "--write" ]; then
  echo "usage: $0 [--write]" >&2
  exit 2
fi

status=0

echo "== GALA provenance =="
echo "gala version: $(gala version 2>&1 | tail -1)"
echo "which gala:   $(command -v gala)"
echo "flake rev:    $(jq -r '.nodes.gala.locked.rev' "$REPO_ROOT/flake.lock")"

recorded_rev=""
recorded_compiler=""
recorded_extraction=""
if [ -f "$PROVENANCE_FILE" ]; then
  echo "recorded provenance:"
  sed 's/^/  /' "$PROVENANCE_FILE"
  recorded_rev="$(sed -n 's/^flake_rev: //p' "$PROVENANCE_FILE")"
  recorded_compiler="$(sed -n 's/^compiler: //p' "$PROVENANCE_FILE")"
  recorded_extraction="$(sed -n 's/^extraction: //p' "$PROVENANCE_FILE")"
else
  echo "recorded provenance: MISSING ($PROVENANCE_FILE)"
  echo "PROVENANCE: $PROVENANCE_FILE is missing; run a bump iteration and record it"
  status=1
fi

current_compiler="$(gala version 2>&1 | tail -1)"
if [ -f "$PROVENANCE_FILE" ] && [ "$recorded_compiler" != "$current_compiler" ]; then
  echo "PROVENANCE: $PROVENANCE_FILE records compiler '$recorded_compiler' but gala reports '$current_compiler'; run a bump iteration"
  status=1
fi

locked_rev="$(jq -r '.nodes.gala.locked.rev' "$REPO_ROOT/flake.lock")"
if [ -n "$recorded_rev" ] && [ "$recorded_rev" != "$locked_rev" ]; then
  echo "PROVENANCE: $PROVENANCE_FILE records $recorded_rev but flake.lock locks $locked_rev; run a bump iteration"
  status=1
fi

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

gofmt_targets=()
twin_count=0

while IFS= read -r -d '' src; do
  rel="${src#./}"
  dir="$(dirname "$rel")"
  name="$(basename "$rel" .gala)"
  generated="$dir/$name.go"
  scratch="$tmp_dir/$(printf '%s' "$rel" | tr '/.' '__').go"

  if [ ! -f "$SERVER_DIR/$generated" ]; then
    echo "MISSING: $rel has no committed twin at $generated"
    status=1
    continue
  fi
  if ! (cd "$SERVER_DIR/$dir" && gala transpile --stdlib-module "$STDLIB_MODULE" -i "$name.gala" -o "$scratch" >/dev/null 2>&1); then
    echo "TRANSPILE: $rel does not transpile"
    status=1
    continue
  fi

  twin_count=$((twin_count + 1))
  gofmt_targets+=("$SERVER_DIR/$generated")

  if grep -Eq '"martianoff/gala' "$scratch"; then
    echo "RUNTIME: $rel generates Go that imports the banned martianoff/gala runtime; only $STDLIB_MODULE imports are allowed"
    status=1
  fi

  if [ "$MODE" = "--write" ]; then
    if ! cmp -s "$SERVER_DIR/$generated" "$scratch"; then
      cp "$scratch" "$SERVER_DIR/$generated"
      echo "WRITE: $generated"
    fi
  elif ! cmp -s "$SERVER_DIR/$generated" "$scratch"; then
    echo "DRIFT: $generated does not regenerate byte-identically"
    status=1
  fi
done < <(cd "$SERVER_DIR" && find . -type f -name '*.gala' -not -path './.gala/*' -not -path './scripts/gala/probes/*' -print0 | sort -z)

if [ "${#gofmt_targets[@]}" -gt 0 ]; then
  unformatted="$(gofmt -l "${gofmt_targets[@]}")"
  if [ -n "$unformatted" ]; then
    echo "GOFMT:"
    echo "$unformatted"
    status=1
  fi
fi

while IFS= read -r -d '' gen; do
  rel="${gen#./}"
  if [ "$(head -n1 "$SERVER_DIR/$rel")" = "$GENERATED_HEADER" ] && [ ! -f "$SERVER_DIR/${rel%.go}.gala" ]; then
    echo "ORPHAN: $rel carries the generated header but ${rel%.go}.gala is missing"
    status=1
  fi
done < <(cd "$SERVER_DIR" && find . -type f -name '*.go' -not -path './.gala/*' -not -path './scripts/gala/probes/*' -print0 | sort -z)

if [ -n "$recorded_extraction" ]; then
  extraction_version="${recorded_extraction%% *}"
  marker_path="$HOME/.gala/stdlib/v$extraction_version/.stdlib-extracted"
  current_marker=""
  if [ -f "$marker_path" ]; then
    current_marker="$(cat "$marker_path")"
  fi
  if [ "$current_marker" != "$recorded_extraction" ]; then
    echo "PROVENANCE: $PROVENANCE_FILE records extraction '$recorded_extraction' but $marker_path is '$current_marker'; run a bump iteration"
    status=1
  fi
elif [ -f "$PROVENANCE_FILE" ]; then
  echo "PROVENANCE: $PROVENANCE_FILE records no extraction fingerprint; run a bump iteration and record it"
  status=1
fi

echo "== go build ./... =="
if ! (cd "$SERVER_DIR" && go build ./...); then
  echo "BUILD: go build ./... failed"
  status=1
fi

if [ "$status" -ne 0 ]; then
  echo "verify.sh: FAILED"
  exit 1
fi
echo "verify.sh: OK ($twin_count twins)"
