// Code generated by GALA transpiler. DO NOT EDIT.

package discord_bot

import (
	"github.com/bwmarrin/discordgo"
	"martianoff/gala/go_interop"
	"os"
	"regexp"
	"timeful/server/discord_bot/commands"
	"timeful/server/logger"
	"timeful/server/utils"
)

//line init.gala:14
var BotId string

//line init.gala:15
var bot *discordgo.Session

//line init.gala:16
var listeningChannel *discordgo.Channel

//line init.gala:17
var commandMap = go_interop.MapEmpty[string, commands.Command]()

//line init.gala:19
func listeningChannelName() string {
//line init.gala:20
	var configuredChannel = os.Getenv("DISCORD_BOT_CHANNEL")
//line init.gala:21
	if configuredChannel != "" {
//line init.gala:22
		return configuredChannel
	}
//line init.gala:24
	if utils.IsRelease() {
//line init.gala:25
		return "timeful-bot"
	}
//line init.gala:27
	return "timeful-bot-dev"
}

//line init.gala:30
func Init() {
//line init.gala:31
	var token = os.Getenv("DISCORD_BOT_TOKEN")
//line init.gala:32
	var guildId = os.Getenv("GUILD_ID")
//line init.gala:33
	var botSession, err = discordgo.New("Bot " + token)
//line init.gala:34
	bot = botSession
//line init.gala:35
	if err != nil {
//line init.gala:36
		logger.StdErr.Panicln(err)
	}
//line init.gala:39
	var u, userErr = bot.User("@me")
//line init.gala:40
	if userErr != nil {
//line init.gala:41
		logger.StdErr.Panicln(userErr)
	}
//line init.gala:43
	BotId = u.ID
//line init.gala:45
	err = bot.Open()
//line init.gala:46
	if err != nil {
//line init.gala:47
		logger.StdErr.Panicln(err)
	}
//line init.gala:49
	logger.StdOut.Println("Discord bot initialized")
//line init.gala:51
	var channelName = listeningChannelName()
//line init.gala:52
	var channels, _ = bot.GuildChannels(guildId)
//line init.gala:53
	for _, channel := range channels {
//line init.gala:54
		if channel.Name == channelName {
//line init.gala:55
			listeningChannel = channel
//line init.gala:56
			break
		}
	}
//line init.gala:60
	commands.Init()
//line init.gala:61
	for _, command := range commands.Commands {
//line init.gala:62
		commandMap[command.Name] = command
	}
//line init.gala:65
	bot.AddHandler(messageHandler)
}

//line init.gala:68
func SendMessage(message string) {
//line init.gala:69
	_, _ = bot.ChannelMessageSend(listeningChannel.ID, message)
}

//line init.gala:72
func messageHandler(s *discordgo.Session, m *discordgo.MessageCreate) {
//line init.gala:73
	if m.ChannelID != listeningChannel.ID {
//line init.gala:74
		return
	}
//line init.gala:76
	if m.Author.ID == BotId {
//line init.gala:77
		return
	}
//line init.gala:80
	var re = regexp.MustCompile(" +")
//line init.gala:81
	var args = re.Split(m.Content, -1)
//line init.gala:82
	var commandName = args[0]
//line init.gala:83
	args = go_interop.SliceFrom(args, 1)
//line init.gala:85
	var command, ok = commandMap[commandName]
//line init.gala:86
	if ok {
//line init.gala:87
		command.Execute(s, m, args)
	}
}
