// Code generated by GALA transpiler. DO NOT EDIT.

package observability

import (
	"regexp"
	"strings"
	"unicode/utf8"
)

//line redact.gala:8

// redactedValue replaces every credential-bearing capture group.
var redactedValue = "[REDACTED]"

//line redact.gala:11

// urlUserInfoPattern matches URL userinfo, for example https://user:password@host/path.
var urlUserInfoPattern = regexp.MustCompile(`([a-zA-Z][a-zA-Z0-9+.\-]*://)([^/@\s]+)@`)

//line redact.gala:14

// schemeCredentialPattern matches Bearer and Basic scheme credentials.
var schemeCredentialPattern = regexp.MustCompile(`(?i)\b(bearer|basic)\s+[A-Za-z0-9._~+/=\-]{6,}`)

//line redact.gala:17

// credentialFieldPattern matches credential-bearing headers and fields, including
// JSON forms. Unquoted values stop at a query separator so following parameters survive.
var credentialFieldPattern = regexp.MustCompile(`(?i)\b(authorization|proxy-authorization|cookie|set-cookie|x-api-key|api[-_]?key|password|passwd|secret|token|access_token|refresh_token|id_token|edit_token|editToken|owner_token)\b("?)(\s*[:=]\s*)("[^"]*"|'[^']*'|[^&\n]+)`)

//line redact.gala:21

// sensitiveQueryPattern matches token, secret, credential, and OAuth-code query parameters.
var sensitiveQueryPattern = regexp.MustCompile(`(?i)([?&][^=&\s#]*(?:token|secret|password|passwd|api[-_]?key|credential|auth|code|otp)[^=&\s#]*=)[^&#\s]*`)

//line redact.gala:24

// Redact removes credentials, secrets, and token-bearing URLs and headers from
// a diagnostic string. Structured records never carry raw requests, so this is
// the defense-in-depth pass over error context that originated in a handler.
// value: the diagnostic string to redact.
func Redact(value string) string {
//line redact.gala:30
	if value == "" {
//line redact.gala:31
		return value
	}
//line redact.gala:33
	var redacted = urlUserInfoPattern.ReplaceAllString(value, "${1}"+redactedValue+"@")
//line redact.gala:34
	redacted = schemeCredentialPattern.ReplaceAllString(redacted, "${1} "+redactedValue)
//line redact.gala:35
	redacted = credentialFieldPattern.ReplaceAllString(redacted, "${1}${2}${3}"+redactedValue)
//line redact.gala:36
	redacted = sensitiveQueryPattern.ReplaceAllString(redacted, "${1}"+redactedValue)
//line redact.gala:37
	return redacted
}

//line redact.gala:39

// truncate bounds a redacted value so a single record can never grow without
// limit from captured error context. The result is always valid UTF-8, because
// an invalid string attribute makes protobuf marshalling fail for the whole
// export batch.
// value: the string to bound.
// limit: the maximum byte length of the result.
func truncate(value string, limit int) string {
//line redact.gala:47
	value = strings.ToValidUTF8(value, "\uFFFD")
//line redact.gala:48
	if len(value) <= limit {
//line redact.gala:49
		return value
	}
//line redact.gala:51
	var trimmed = ""
//line redact.gala:52
	var cut = ""
//line redact.gala:53
	var used = 0
//line redact.gala:54
	var lastSpaceIndex = -1
//line redact.gala:55
	for _, r := range value {
//line redact.gala:56
		var size = utf8.RuneLen(r)
//line redact.gala:57
		if used+size > limit {
//line redact.gala:58
			break
		}
//line redact.gala:60
		if r == ' ' || r == '\t' || r == '\n' {
//line redact.gala:61
			cut = trimmed
//line redact.gala:62
			lastSpaceIndex = used
		}
//line redact.gala:64
		trimmed = trimmed + string(r)
//line redact.gala:65
		used = used + size
	}
//line redact.gala:67
	if lastSpaceIndex > limit/2 {
//line redact.gala:68
		trimmed = cut
	}
//line redact.gala:70
	return trimmed + "..."
}
