// Code generated by GALA transpiler. DO NOT EDIT.

package observability

import (
	"regexp"
	"strings"
	"unicode/utf8"
)

//line redact.gala:10
var redactedValue = "[REDACTED]"

//line redact.gala:13
var urlUserInfoPattern = regexp.MustCompile(`([a-zA-Z][a-zA-Z0-9+.\-]*://)([^/@\s]+)@`)

//line redact.gala:16
var schemeCredentialPattern = regexp.MustCompile(`(?i)\b(bearer|basic)\s+[A-Za-z0-9._~+/=\-]{6,}`)

//line redact.gala:20
var credentialFieldPattern = regexp.MustCompile(`(?i)\b(authorization|proxy-authorization|cookie|set-cookie|x-api-key|api[-_]?key|password|passwd|secret|token|access_token|refresh_token|id_token|edit_token|editToken|owner_token)\b("?)(\s*[:=]\s*)("[^"]*"|'[^']*'|[^&\n]+)`)

//line redact.gala:23
var sensitiveQueryPattern = regexp.MustCompile(`(?i)([?&][^=&\s#]*(?:token|secret|password|passwd|api[-_]?key|credential|auth|code|otp)[^=&\s#]*=)[^&#\s]*`)

//line redact.gala:29
func Redact(value string) string {
//line redact.gala:30
	if value == "" {
//line redact.gala:31
		return value
	}
//line redact.gala:33
	var redacted = urlUserInfoPattern.ReplaceAllString(value, "${1}"+redactedValue+"@")
//line redact.gala:34
	redacted = schemeCredentialPattern.ReplaceAllString(redacted, "${1} "+redactedValue)
//line redact.gala:35
	redacted = credentialFieldPattern.ReplaceAllString(redacted, "${1}${2}${3}"+redactedValue)
//line redact.gala:36
	redacted = sensitiveQueryPattern.ReplaceAllString(redacted, "${1}"+redactedValue)
//line redact.gala:37
	return redacted
}

//line redact.gala:46
func truncate(value string, limit int) string {
//line redact.gala:47
	value = strings.ToValidUTF8(value, "\uFFFD")
//line redact.gala:48
	if len(value) <= limit {
//line redact.gala:49
		return value
	}
//line redact.gala:51
	var trimmed = ""
//line redact.gala:52
	var cut = ""
//line redact.gala:53
	var used = 0
//line redact.gala:54
	var lastSpaceIndex = -1
//line redact.gala:55
	for _, r := range value {
//line redact.gala:56
		var size = utf8.RuneLen(r)
//line redact.gala:57
		if used+size > limit {
//line redact.gala:58
			break
		}
//line redact.gala:60
		if r == ' ' || r == '\t' || r == '\n' {
//line redact.gala:61
			cut = trimmed
//line redact.gala:62
			lastSpaceIndex = used
		}
//line redact.gala:64
		trimmed = trimmed + string(r)
//line redact.gala:65
		used = used + size
	}
//line redact.gala:67
	if lastSpaceIndex > limit/2 {
//line redact.gala:68
		trimmed = cut
	}
//line redact.gala:70
	return trimmed + "..."
}
