// Code generated by GALA transpiler. DO NOT EDIT.

package commands

import "fmt"
import "go.gala.fyi/stdlib/std"
import (
	"context"
	"encoding/json"
	"net/url"
	"strconv"
	"time"
	"timeful/server/logger"
	pgstore "timeful/server/postgres"
	"timeful/server/utils"
)

//line active_users.gala:15
func executeActiveUsers(args []string, webhookUrl string) {
//line active_users.gala:16
	var err error
//line active_users.gala:19
	var list = false
//line active_users.gala:20
	var days = 7
//line active_users.gala:21
	if len(args) >= 1 {
//line active_users.gala:22
		if args[0] == "true" {
//line active_users.gala:23
			list = true
		} else if args[0] == "false" {
//line active_users.gala:25
			list = false
		} else {
//line active_users.gala:27
			SendRawMessage(newResponse("ephemeral", fmt.Sprintf("LIST=%s is not a valid boolean!", args[0])), webhookUrl)
//line active_users.gala:28
			return
		}
	}
//line active_users.gala:31
	if len(args) >= 2 {
//line active_users.gala:32
		days, err = strconv.Atoi(args[1])
//line active_users.gala:33
		if err != nil {
//line active_users.gala:34
			SendRawMessage(newResponse("ephemeral", fmt.Sprintf("DAYS=%s is not a valid number!", args[1])), webhookUrl)
//line active_users.gala:35
			return
		}
	}
//line active_users.gala:42
	var startDate = std.NewImmutable(utils.GetDateAtTime(time.Now().AddDate(0, 0, -days), "00:00:00"))
//line active_users.gala:44
	var (
		_tmp_1, _tmp_2 = pgstore.DefaultRepository()
		repository     = std.NewImmutable(_tmp_1)
		repoErr        = std.NewImmutable(_tmp_2)
	)
//line active_users.gala:45
	if repoErr.Get() != nil {
//line active_users.gala:46
		logger.StdErr.Panicln(repoErr.Get())
	}
//line active_users.gala:48
	var (
		_tmp_3, _tmp_4 = repository.Get().ListActiveUserDays(context.Background(), startDate.Get(), time.Now())
		logs           = std.NewImmutable(_tmp_3)
		logsErr        = std.NewImmutable(_tmp_4)
	)
//line active_users.gala:49
	if logsErr.Get() != nil {
//line active_users.gala:50
		logger.StdErr.Panicln(logsErr.Get())
	}
//line active_users.gala:54
	var dayStrings = std.NewImmutable(activeUsersDayStrings())
//line active_users.gala:56
	if list {
//line active_users.gala:58
		SendRawMessage(newResponse("in_channel", "Active Users:\n"), webhookUrl)
//line active_users.gala:59
		var message = ""
//line active_users.gala:60
		for _, log := range logs.Get() {
//line active_users.gala:61
			var date = std.NewImmutable(log.LogDate)
//line active_users.gala:62
			message += dayStrings.Get()[date.Get().Weekday()] + " "
//line active_users.gala:63
			message += utils.GetDateString(date.Get()) + " | "
//line active_users.gala:64
			message += fmt.Sprintf("Count: %d\n", activeUsersMembersCount(log))
//line active_users.gala:66
			for _, user := range log.Members {
//line active_users.gala:67
				message += fmt.Sprintf("\t- %v %v (%v)\n", user.FirstName, user.LastName, user.Email)
			}
		}
//line active_users.gala:71
		for _, msg := range splitLongMessage(message, "```") {
//line active_users.gala:72
			SendRawMessage(newResponse("in_channel", msg), webhookUrl)
		}
	} else {
//line active_users.gala:78
		var labels = activeUsersEmptyLabels()
//line active_users.gala:79
		var data = activeUsersEmptyData()
//line active_users.gala:80
		for i := activeUsersLogsCount(logs.Get()) - 1; i >= 0; i-- {
//line active_users.gala:81
			labels = activeUsersAppendLabel(labels, utils.GetDateString(logs.Get()[i].LogDate))
//line active_users.gala:82
			data = activeUsersAppendCount(data, activeUsersMembersCount(logs.Get()[i]))
		}
//line active_users.gala:86
		var chart = std.NewImmutable(activeUsersChart(labels, data))
//line active_users.gala:87
		var (
			_tmp_5, _ = json.Marshal(chart.Get())
			jsonStr   = std.NewImmutable(_tmp_5)
		)
//line active_users.gala:89
		var encodedChart = std.NewImmutable(url.PathEscape(string(jsonStr.Get())))
//line active_users.gala:90
		var chartUrl = std.NewImmutable(fmt.Sprintf("https://quickchart.io/chart?c=%s&backgroundColor=white", encodedChart.Get()))
//line active_users.gala:92
		SendRawMessage(activeUsersChartResponse(chartUrl.Get()), webhookUrl)
	}
}

//line active_users.gala:96
var activeUsers Command = Command{Name: "/active_users", Description: `Gets the number of active users in the database, based on last sign in date. 
  - if LIST is true, it will list the name/email of all users, otherwise, it will show a bar graph
  - DAYS is the amount of days since last sign in
  `, Usage: "/active_users [LIST=false] [DAYS=7]", Execute: executeActiveUsers}
