// Code generated by GALA transpiler. DO NOT EDIT.

package commands

import "fmt"
import "go.gala.fyi/stdlib/std"
import (
	"context"
	"timeful/server/logger"
	"timeful/server/postgres"
)

//line num_users.gala:10
func executeNumUsers(args []string, webhookUrl string) {
//line num_users.gala:11
	var repository = std.NewImmutable(std.GoTry(postgres.DefaultRepository()).OnFailure(func(err error) {
		logger.StdErr.Panicln(err)
	}).Get())
//line num_users.gala:12
	var n = std.NewImmutable(std.GoTry(repository.Get().CountAccounts(context.Background())).OnFailure(func(err error) {
		logger.StdErr.Panicln(err)
	}).Get())
//line num_users.gala:14
	SendRawMessage(newResponse("in_channel", fmt.Sprintf("Number of currently signed up users: %d", n.Get())), webhookUrl)
}

//line num_users.gala:17
var numUsers Command = Command{Name: "/num_users", Description: "Returns the number of signed up users", Execute: executeNumUsers}
