// Code generated by GALA transpiler. DO NOT EDIT.

package appenv

import (
	"os"
	"strings"
)

//line appenv.gala:8
type Environment = string

//line appenv.gala:10
var Development Environment = "development"

//line appenv.gala:11
var Test Environment = "test"

//line appenv.gala:12
var Staging Environment = "staging"

//line appenv.gala:13
var Production Environment = "production"

//line appenv.gala:15
func Parse(value string) Environment {
//line appenv.gala:16
	var normalized = strings.ToLower(strings.TrimSpace(value))
//line appenv.gala:17
	if normalized == string(Development) {
//line appenv.gala:18
		return Development
	}
//line appenv.gala:20
	if normalized == string(Test) {
//line appenv.gala:21
		return Test
	}
//line appenv.gala:23
	if normalized == string(Staging) {
//line appenv.gala:24
		return Staging
	}
//line appenv.gala:26
	if normalized == string(Production) {
//line appenv.gala:27
		return Production
	}
//line appenv.gala:29
	return Development
}

//line appenv.gala:32
func Current() Environment {
//line appenv.gala:33
	return Parse(os.Getenv("APP_ENV"))
}

//line appenv.gala:36
func IsProductionLike(env Environment) bool {
//line appenv.gala:37
	return env == Staging || env == Production
}

//line appenv.gala:40
func ShouldUseReleaseMode(ginMode string, env Environment) bool {
//line appenv.gala:41
	var normalized = strings.ToLower(strings.TrimSpace(ginMode))
//line appenv.gala:42
	if normalized == "debug" || normalized == string(Development) {
//line appenv.gala:43
		return false
	}
//line appenv.gala:45
	if normalized == "release" || normalized == string(Production) {
//line appenv.gala:46
		return true
	}
//line appenv.gala:48
	return IsProductionLike(env)
}

//line appenv.gala:51
func Port(env Environment) string {
//line appenv.gala:52
	if env == Test {
//line appenv.gala:53
		return "3003"
	}
//line appenv.gala:55
	if env == Staging {
//line appenv.gala:56
		return "3004"
	}
//line appenv.gala:58
	if env == Production {
//line appenv.gala:59
		return "3005"
	}
//line appenv.gala:61
	return "3002"
}
