// Code generated by GALA transpiler. DO NOT EDIT.

package appenv

import "go.gala.fyi/stdlib/std"
import (
	"os"
	"strings"
)

//line appenv.gala:7

// Environment is the application environment selected by APP_ENV.
type Environment string

func (s Environment) Hash() uint32 {
	return std.HashString(string(s))
}
func (s Environment) Compare(other Environment) int {
	return std.CompareString(string(s), string(other))
}

//line appenv.gala:11
var Development Environment = "development"

//line appenv.gala:12
var Test Environment = "test"

//line appenv.gala:13
var Staging Environment = "staging"

//line appenv.gala:14
var Production Environment = "production"

//line appenv.gala:16
func normalize(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

//line appenv.gala:18
func Parse(value string) Environment {
	return func(obj Environment) Environment {
		if obj == Test {
			return Test
		} else if obj == Staging {
			return Staging
		} else if obj == Production {
			return Production
		} else {
			return Development
		}
	}(Environment(normalize(value)))
}

//line appenv.gala:25
func Current() Environment {
	return Parse(os.Getenv("APP_ENV"))
}

//line appenv.gala:27
func IsProductionLike(env Environment) bool {
	return env == Staging || env == Production
}

//line appenv.gala:29
func ShouldUseReleaseMode(ginMode string, env Environment) bool {
	return func(obj string) bool {
		{
			mode := obj
			if true && (mode == "debug" || mode == string(Development)) {
				return false
			} else {
				mode := obj
				if true && (mode == "release" || mode == string(Production)) {
					return true
				} else {
					return IsProductionLike(env)
				}
			}
		}
	}(normalize(ginMode))
}

//line appenv.gala:35
func Port(env Environment) string {
	return func(obj Environment) string {
		if obj == Test {
			return "3003"
		} else if obj == Staging {
			return "3004"
		} else if obj == Production {
			return "3005"
		} else {
			return "3002"
		}
	}(env)
}
