// Code generated by GALA transpiler. DO NOT EDIT.

package providerconfig

import (
	"os"
	"strings"
)

//line providerconfig.gala:8
var TestGoogleOAuthTokenEndpoint = "TEST_GOOGLE_OAUTH_TOKEN_ENDPOINT"

//line providerconfig.gala:9
var TestGoogleCalendarAPIBaseURL = "TEST_GOOGLE_CALENDAR_API_BASE_URL"

//line providerconfig.gala:10
var TestMicrosoftOAuthTokenEndpoint = "TEST_MICROSOFT_OAUTH_TOKEN_ENDPOINT"

//line providerconfig.gala:11
var TestMicrosoftGraphAPIBaseURL = "TEST_MICROSOFT_GRAPH_API_BASE_URL"

//line providerconfig.gala:13
var realGoogleOAuthTokenEndpoint = "https://oauth2.googleapis.com/token"

//line providerconfig.gala:14
var realGoogleCalendarAPIBaseURL = "https://www.googleapis.com/calendar/v3"

//line providerconfig.gala:15
var realMicrosoftOAuthTokenEndpoint = "https://login.microsoftonline.com/common/oauth2/v2.0/token"

//line providerconfig.gala:16
var realMicrosoftGraphAPIBaseURL = "https://graph.microsoft.com/v1.0"

//line providerconfig.gala:18
func overrideOrDefault(envName string, fallback string) string {
//line providerconfig.gala:19
	var value = strings.TrimSpace(os.Getenv(envName))
//line providerconfig.gala:20
	if value != "" {
//line providerconfig.gala:21
		return value
	}
//line providerconfig.gala:23
	return fallback
}

//line providerconfig.gala:26
func GoogleOAuthTokenEndpoint() string {
//line providerconfig.gala:27
	return overrideOrDefault(TestGoogleOAuthTokenEndpoint, realGoogleOAuthTokenEndpoint)
}

//line providerconfig.gala:30
func GoogleCalendarAPIBaseURL() string {
//line providerconfig.gala:31
	return strings.TrimRight(overrideOrDefault(TestGoogleCalendarAPIBaseURL, realGoogleCalendarAPIBaseURL), "/")
}

//line providerconfig.gala:37
func MicrosoftOAuthTokenEndpoint() string {
//line providerconfig.gala:38
	return overrideOrDefault(TestMicrosoftOAuthTokenEndpoint, realMicrosoftOAuthTokenEndpoint)
}

//line providerconfig.gala:41
func MicrosoftGraphAPIBaseURL() string {
//line providerconfig.gala:42
	return strings.TrimRight(overrideOrDefault(TestMicrosoftGraphAPIBaseURL, realMicrosoftGraphAPIBaseURL), "/")
}
