// Code generated by GALA transpiler. DO NOT EDIT.

package routes

import "fmt"
import "go.gala.fyi/stdlib/std"
import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"
	"timeful/server/accounts"
	"timeful/server/errs"
	"timeful/server/models"
	"timeful/server/postgres"
	"timeful/server/respondents"
	"timeful/server/responses"
	"timeful/server/services/listmonk"
	"timeful/server/utils"
)
import "go.gala.fyi/stdlib/go_interop"

//line group.gala:31
var groupInviteEmailTemplate = 9

//line group.gala:32
var groupUpdateEmailTemplate = 11

//line group.gala:33

// accountEmail resolves the signed-in account's email through the
// authoritative account boundary, adopting a legacy session once if needed.
func accountEmail(ctx context.Context, platformIdentityID string) string {
//line group.gala:37
	if platformIdentityID == "" {
//line group.gala:38
		return ""
	}
//line group.gala:40
	var account, err = accounts.Resolve(ctx, platformIdentityID)
//line group.gala:41
	if err != nil || account == nil {
//line group.gala:42
		return ""
	}
//line group.gala:44
	return account.Email
}

//line group.gala:46

// groupViewerIsInvitee reports whether the signed-in viewer is a
// non-declined member of the group, which is required to expose respondent
// emails for matching pending attendees to respondents. The membership check is
// a repository EXISTS over event_attendees (event_id, lower(email)) rather than
// an in-memory scan of the loaded attendee list.
func groupViewerIsInvitee(ctx context.Context, repository *postgres.Repository, eventID string, viewer *visitor) bool {
//line group.gala:53
	var email = std.NewImmutable(accountEmail(ctx, viewer.platformIdentityID))
//line group.gala:54
	if email.Get() == "" {
//line group.gala:55
		return false
	}
//line group.gala:57
	var invitee, err = repository.HasNonDeclinedAttendeeEmail(ctx, eventID, email.Get())
//line group.gala:58
	return err == nil && invitee
}

//line group.gala:60

// groupEmailVisibility keeps respondent emails visible to the owner and
// non-declined invitees so clients can match pending attendees to respondents
// when collectEmails is off, mirroring legacy group behavior. The repository does
// not persist a denormalized account snapshot, so the response email is
// promoted into the rebuilt user snapshot at read time.
func groupEmailVisibility(ctx context.Context, repository *postgres.Repository, eventID string, value models.Event, viewer *visitor, responseMap map[string]*publicResponse) {
//line group.gala:67
	if responseMap == nil {
//line group.gala:68
		return
	}
//line group.gala:70
	var showEmails = std.NewImmutable(viewer.owner && utils.Coalesce(value.CollectEmails))
//line group.gala:71
	var keepGroupEmails = std.NewImmutable(viewer.owner || groupViewerIsInvitee(ctx, repository, eventID, viewer))
//line group.gala:72
	for key, response := range responseMap {
//line group.gala:73
		if response == nil {
//line group.gala:74
			continue
		}
//line group.gala:76
		if keepGroupEmails.Get() && response.Email != "" && response.User == nil {
//line group.gala:77
			response.User = &models.User{Email: response.Email}
		}
//line group.gala:79
		stripSensitiveUserFields(response.User)
//line group.gala:80
		if !showEmails.Get() {
//line group.gala:81
			response.Email = ""
//line group.gala:82
			if response.User != nil && !keepGroupEmails.Get() {
//line group.gala:83
				response.User.Email = ""
			}
		}
//line group.gala:86
		responseMap[key] = response
	}
}

//line group.gala:89

// groupViewerHasResponded reports whether the calling visitor owns a
// response on the group, either through a signed-in account response or the
// browser Event Visitor Identity. It backs the derived hasResponded read.
func groupViewerHasResponded(ctx context.Context, repo *postgres.Repository, event *postgres.Event, viewer *visitor) bool {
//line group.gala:94
	if viewer == nil {
//line group.gala:95
		return false
	}
//line group.gala:97
	if viewer.platformIdentityID != "" {
//line group.gala:98
		var _, err = repo.GetResponseByPlatformIdentityID(ctx, event.ID, viewer.platformIdentityID)
//line group.gala:99
		if err == nil {
//line group.gala:100
			return true
		}
//line group.gala:102
		if !errors.Is(err, pgx.ErrNoRows) {
//line group.gala:103
			return false
		}
	}
//line group.gala:106
	if viewer.identity == nil {
//line group.gala:107
		return false
	}
//line group.gala:109
	var hasResponded, err = repo.EventVisitorHasResponse(ctx, event.ID, viewer.identity.ID)
//line group.gala:110
	if err != nil {
//line group.gala:111
		return false
	}
//line group.gala:113
	return hasResponded
}

//line group.gala:115

// sendGroupInviteEmails sends the existing availability-group
// invitation email to each newly added invitee.
func sendGroupInviteEmails(ownerName string, groupName string, groupURL string, emails []string) {
//line group.gala:119
	for _, email := range emails {
//line group.gala:120
		if strings.TrimSpace(email) == "" {
//line group.gala:121
			continue
		}
//line group.gala:123
		var data = std.NewImmutable(go_interop.MapEmpty[string, any]())
//line group.gala:124
		go_interop.MapPut[string, any](data.Get(), "ownerName", ownerName)
//line group.gala:125
		go_interop.MapPut[string, any](data.Get(), "groupName", groupName)
//line group.gala:126
		go_interop.MapPut[string, any](data.Get(), "groupUrl", groupURL)
//line group.gala:127
		listmonk.SendEmailAddSubscriberIfNotExist(email, groupInviteEmailTemplate, data.Get(), false)
	}
}

//line group.gala:130

// sendGroupUpdateEmails sends invitation emails to added members and
// the existing group update email to kept members, matching legacy ordering.
func sendGroupUpdateEmails(ownerName string, groupName string, groupURL string, added []string, kept []string) {
//line group.gala:134
	sendGroupInviteEmails(ownerName, groupName, groupURL, added)
//line group.gala:135
	if len(added) == 0 {
//line group.gala:136
		return
	}
//line group.gala:138
	for _, email := range kept {
//line group.gala:139
		if strings.TrimSpace(email) == "" {
//line group.gala:140
			continue
		}
//line group.gala:142
		var data = std.NewImmutable(go_interop.MapEmpty[string, any]())
//line group.gala:143
		go_interop.MapPut[string, any](data.Get(), "ownerName", ownerName)
//line group.gala:144
		go_interop.MapPut[string, any](data.Get(), "groupName", groupName)
//line group.gala:145
		go_interop.MapPut[string, any](data.Get(), "groupUrl", groupURL)
//line group.gala:146
		go_interop.MapPut[string, any](data.Get(), "emails", added)
//line group.gala:147
		listmonk.SendEmailAddSubscriberIfNotExist(email, groupUpdateEmailTemplate, data.Get(), false)
	}
}

//line group.gala:151
func groupURL(shortID string) string {
	return fmt.Sprintf("%s/g/%s", utils.GetBaseUrl(), shortID)
}

//line group.gala:152

// groupEmailPlan carries the owner-facing email work computed while the
// event row is locked so it can be sent after the transaction commits.
type groupEmailPlan struct {
	ownerName string
	groupName string
	added     []string
	kept      []string
}

func (s groupEmailPlan) Copy() groupEmailPlan {
	return groupEmailPlan{ownerName: std.Copy(s.ownerName), groupName: std.Copy(s.groupName), added: std.Copy(s.added), kept: std.Copy(s.kept)}
}
func (s groupEmailPlan) Equal(other groupEmailPlan) bool {
	return std.Equal(s.ownerName, other.ownerName) && std.Equal(s.groupName, other.groupName) && std.Equal(s.added, other.added) && std.Equal(s.kept, other.kept)
}

//line group.gala:161

// applyGroupAttendeeEdits diffs the requested attendee emails against
// the stored membership, removes departed members' account responses so the
// response count stays correct, and returns the post-commit email plan. The
// owner membership is protected from removal. The caller already holds the
// event row lock and persists the adjusted response count.
func applyGroupAttendeeEdits(ctx context.Context, tx *postgres.Repository, event *postgres.Event, requested []string) (groupEmailPlan, error) {
	var _goResult std.Try[groupEmailPlan] = func() std.Try[groupEmailPlan] {
//line group.gala:168
		var plan = groupEmailPlan{ownerName: groupOwnerName(ctx, event.OwnerPlatformIdentityID), groupName: event.Name, added: nil, kept: nil}
//line group.gala:172
		var current, listErr = tx.ListAttendees(ctx, event.ID)
//line group.gala:173
		if listErr != nil {
//line group.gala:174
			return std.Failure[groupEmailPlan]{}.Apply(listErr)
		}
//line group.gala:176
		var currentEmails = go_interop.SliceWithCapacity[string](len(go_interop.SliceFrom(current, 0)))
//line group.gala:177
		var byEmail = go_interop.MapWithCapacity[string, postgres.Attendee](len(go_interop.SliceFrom(current, 0)))
//line group.gala:178
		for _, attendee := range current {
//line group.gala:179
			currentEmails = go_interop.SliceAppend(currentEmails, attendee.Email)
//line group.gala:180
			byEmail[strings.ToLower(strings.TrimSpace(attendee.Email))] = attendee
		}
//line group.gala:182
		var added, removed, kept = utils.FindAddedRemovedKept(requested, currentEmails)
//line group.gala:183
		var removedEmails = go_interop.SliceWithCapacity[string](len(go_interop.SliceFrom(removed, 0)))
//line group.gala:184
		var removedIdentityIDs = go_interop.SliceWithCapacity[string](len(go_interop.SliceFrom(removed, 0)))
//line group.gala:185
		for _, item := range removed {
//line group.gala:186
			var attendee = std.NewImmutable(byEmail[strings.ToLower(strings.TrimSpace(item.Value))])
//line group.gala:187
			if attendee.Get().PlatformIdentityID != nil && event.OwnerPlatformIdentityID != nil && *attendee.Get().PlatformIdentityID == *event.OwnerPlatformIdentityID {
//line group.gala:188
				continue
			}
//line group.gala:190
			removedEmails = go_interop.SliceAppend(removedEmails, attendee.Get().Email)
//line group.gala:191
			if attendee.Get().PlatformIdentityID != nil {
//line group.gala:192
				removedIdentityIDs = go_interop.SliceAppend(removedIdentityIDs, *attendee.Get().PlatformIdentityID)
			}
		}
//line group.gala:200
		var deleted, deleteErr = tx.DeleteAccountResponses(ctx, event.ID, removedIdentityIDs)
//line group.gala:201
		if deleteErr != nil {
//line group.gala:202
			return std.Failure[groupEmailPlan]{}.Apply(deleteErr)
		}
//line group.gala:204
		if deleted > 0 {
//line group.gala:205
			event.NumResponses -= int(deleted)
//line group.gala:206
			if event.NumResponses < 0 {
//line group.gala:207
				event.NumResponses = 0
			}
		}
//line group.gala:210
		var removeErr = tx.RemoveAttendees(ctx, event.ID, removedEmails)
//line group.gala:211
		if removeErr != nil {
//line group.gala:212
			return std.Failure[groupEmailPlan]{}.Apply(removeErr)
		}
//line group.gala:214
		var addedEmails = go_interop.SliceWithCapacity[string](len(go_interop.SliceFrom(added, 0)))
//line group.gala:215
		for _, item := range added {
//line group.gala:216
			if strings.TrimSpace(item.Value) == "" {
//line group.gala:217
				continue
			}
//line group.gala:219
			addedEmails = go_interop.SliceAppend(addedEmails, item.Value)
//line group.gala:220
			plan.added = go_interop.SliceAppend(plan.added, item.Value)
		}
//line group.gala:222
		var addErr = tx.AddAttendees(ctx, event.ID, addedEmails, utils.FalsePtr())
//line group.gala:223
		if addErr != nil {
//line group.gala:224
			return std.Failure[groupEmailPlan]{}.Apply(addErr)
		}
//line group.gala:226
		for _, item := range kept {
//line group.gala:227
			plan.kept = go_interop.SliceAppend(plan.kept, item.Value)
		}
//line group.gala:229
		return std.Success[groupEmailPlan]{}.Apply(plan)
	}()
	if _goResult.IsFailure() {
		return *new(groupEmailPlan), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line group.gala:231

// groupOwnerName resolves the owner display name used in group emails.
func groupOwnerName(ctx context.Context, ownerPlatformIdentityID *string) string {
//line group.gala:234
	if ownerPlatformIdentityID == nil || *ownerPlatformIdentityID == "" {
//line group.gala:235
		return "Somebody"
	}
//line group.gala:237
	var account, err = accounts.Resolve(ctx, *ownerPlatformIdentityID)
//line group.gala:238
	if err != nil || account == nil || account.FirstName == "" {
//line group.gala:239
		return "Somebody"
	}
//line group.gala:241
	return account.FirstName
}

//line group.gala:243

// declineInvite sets the attendee decline state for the signed-in
// member of a group. An optional {"declined": false} body covers
// undecline.
// @Summary Decline the current user's invite to the event
// @Tags events
// @Accept json
// @Produce json
// @Param eventId path string true "Event ID"
// @Success 200
// @Router /events/{eventId}/decline [post]
func declineInvite(c *gin.Context) {
//line group.gala:255
	var declined = true
//line group.gala:256
	var body, readErr = io.ReadAll(c.Request.Body)
//line group.gala:257
	if readErr == nil && len(go_interop.SliceFrom(bytes.TrimSpace(body), 0)) > 0 {
//line group.gala:258
		var input declineBody
//line group.gala:259
		if json.Unmarshal(body, &input) == nil && input.Declined != nil {
//line group.gala:260
			declined = *input.Declined
		}
	}
//line group.gala:263
	var repository = defaultRepository(c)
//line group.gala:264
	if repository == nil {
//line group.gala:265
		return
	}
//line group.gala:267
	var event = loadEvent(c, repository)
//line group.gala:268
	if event == nil {
//line group.gala:269
		return
	}
//line group.gala:271
	if event.Type != postgres.EventTypeGroup {
//line group.gala:272
		c.JSON(http.StatusBadRequest, responses.Error{Error: errs.EventNotGroup})
//line group.gala:273
		return
	}
//line group.gala:275
	var userInterface, _ = c.Get("authUser")
//line group.gala:276
	var user = std.NewImmutable(func(obj any) *models.User {
		{
			u, _tmp_1 := std.As[*models.User](obj)
			if _tmp_1 {
				return u
			} else {
				return nil
			}
		}
	}(userInterface))
//line group.gala:280
	if user.Get() == nil {
//line group.gala:281
		c.JSON(http.StatusUnauthorized, responses.Error{Error: errs.NotSignedIn})
//line group.gala:282
		return
	}
//line group.gala:284
	var _, getErr = repository.GetAttendeeByEmail(c.Request.Context(), event.ID, user.Get().Email)
//line group.gala:285
	if getErr != nil {
//line group.gala:286
		if errors.Is(getErr, pgx.ErrNoRows) {
//line group.gala:287
			c.JSON(http.StatusNotFound, responses.Error{Error: errs.AttendeeEmailNotFound})
//line group.gala:288
			return
		}
//line group.gala:290
		mutationError(c, getErr)
//line group.gala:291
		return
	}
//line group.gala:293
	var setErr = repository.SetAttendeeDeclined(c.Request.Context(), event.ID, user.Get().Email, declined)
//line group.gala:294
	if setErr != nil {
//line group.gala:295
		mutationError(c, setErr)
//line group.gala:296
		return
	}
//line group.gala:298
	c.JSON(http.StatusOK, gin.H{})
}

//line group.gala:300

// groupManualAvailability is the day-window map an availability group stores per
// response. Each key is the millisecond instant a day starts and each value
// holds the available instants inside that day.
type groupManualAvailability = map[models.DateTime][]models.DateTime

//line group.gala:305

// decodeGroupManualAvailability normalizes the two JSON encodings the group
// transport can produce: the legacy millisecond-keyed map whose values are
// RFC3339 strings, and the frontend ZonedDateTime-keyed encoding whose values
// are epoch milliseconds. Omitted or null input yields a nil map so an update
// preserves the stored availability.
func decodeGroupManualAvailability(raw json.RawMessage) (groupManualAvailability, error) {
	var _goResult std.Try[groupManualAvailability] = func() std.Try[groupManualAvailability] {
//line group.gala:312
		var trimmed = bytes.TrimSpace(raw)
//line group.gala:313
		if len(go_interop.SliceFrom(trimmed, 0)) == 0 || string(trimmed) == "null" {
//line group.gala:314
			return std.Success[groupManualAvailability]{}.Apply(nil)
		}
//line group.gala:316
		var encoded map[string][]json.RawMessage
//line group.gala:317
		var decodeErr = json.Unmarshal(trimmed, &encoded)
//line group.gala:318
		if decodeErr != nil {
//line group.gala:319
			return std.Failure[groupManualAvailability]{}.Apply(decodeErr)
		}
//line group.gala:321
		var result = groupManualAvailability{}
//line group.gala:322
		for key, values := range encoded {
//line group.gala:323
			var day, dayErr = parseGroupAvailabilityInstant(key)
//line group.gala:324
			if dayErr != nil {
//line group.gala:325
				return std.Failure[groupManualAvailability]{}.Apply(dayErr)
			}
//line group.gala:327
			var instants = go_interop.SliceWithCapacity[models.DateTime](len(go_interop.SliceFrom(values, 0)))
//line group.gala:328
			for _, value := range values {
//line group.gala:329
				var instant, ok, valueErr = parseGroupAvailabilityValue(value)
//line group.gala:330
				if valueErr != nil {
//line group.gala:331
					return std.Failure[groupManualAvailability]{}.Apply(valueErr)
				}
//line group.gala:333
				if ok {
//line group.gala:334
					instants = go_interop.SliceAppend(instants, instant)
				}
			}
//line group.gala:337
			result[day] = instants
		}
//line group.gala:339
		return std.Success[groupManualAvailability]{}.Apply(result)
	}()
	if _goResult.IsFailure() {
		return *new(groupManualAvailability), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line group.gala:342
func parseGroupAvailabilityInstant(value string) (models.DateTime, error) {
	var _goResult std.Try[models.DateTime] = func() std.Try[models.DateTime] {
//line group.gala:343
		var trimmed = strings.TrimSpace(value)
//line group.gala:344
		var millis, parseErr = strconv.ParseInt(trimmed, 10, 64)
//line group.gala:345
		if parseErr == nil {
//line group.gala:346
			return std.Success[models.DateTime]{}.Apply(models.DateTime(millis))
		}
//line group.gala:348
		var instant, timeErr = parseGroupAvailabilityTime(trimmed)
//line group.gala:349
		if timeErr != nil {
//line group.gala:350
			return std.Failure[models.DateTime]{}.Apply(timeErr)
		}
//line group.gala:352
		return std.Success[models.DateTime]{}.Apply(models.NewDateTimeFromTime(instant))
	}()
	if _goResult.IsFailure() {
		return *new(models.DateTime), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line group.gala:355
func parseGroupAvailabilityValue(raw json.RawMessage) (models.DateTime, bool, error) {
	var _goResult std.Try[std.Tuple[models.DateTime, bool]] = func() std.Try[std.Tuple[models.DateTime, bool]] {
//line group.gala:356
		var trimmed = bytes.TrimSpace(raw)
//line group.gala:357
		if len(go_interop.SliceFrom(trimmed, 0)) == 0 || string(trimmed) == "null" {
//line group.gala:358
			return std.Success[std.Tuple[models.DateTime, bool]]{}.Apply(std.Tuple[models.DateTime, bool]{V1: std.NewImmutable(models.DateTime(0)), V2: std.NewImmutable(false)})
		}
//line group.gala:360
		var millis int64
//line group.gala:361
		var millisErr = json.Unmarshal(trimmed, &millis)
//line group.gala:362
		if millisErr == nil {
//line group.gala:363
			return std.Success[std.Tuple[models.DateTime, bool]]{}.Apply(std.Tuple[models.DateTime, bool]{V1: std.NewImmutable(models.DateTime(millis)), V2: std.NewImmutable(true)})
		}
//line group.gala:365
		var encoded string
//line group.gala:366
		var encodedErr = json.Unmarshal(trimmed, &encoded)
//line group.gala:367
		if encodedErr != nil {
//line group.gala:368
			return std.Failure[std.Tuple[models.DateTime, bool]]{}.Apply(encodedErr)
		}
//line group.gala:370
		var instant, timeErr = parseGroupAvailabilityTime(encoded)
//line group.gala:371
		if timeErr != nil {
//line group.gala:372
			return std.Failure[std.Tuple[models.DateTime, bool]]{}.Apply(timeErr)
		}
//line group.gala:374
		return std.Success[std.Tuple[models.DateTime, bool]]{}.Apply(std.Tuple[models.DateTime, bool]{V1: std.NewImmutable(models.NewDateTimeFromTime(instant)), V2: std.NewImmutable(true)})
	}()
	if _goResult.IsFailure() {
		return *new(models.DateTime), *new(bool), _goResult.GetError()
	}
	_goValue := _goResult.Get()
	return _goValue.V1.Get(), _goValue.V2.Get(), nil
}

//line group.gala:376

// parseGroupAvailabilityTime accepts RFC3339 instants and Temporal's RFC9557
// ZonedDateTime string form whose trailing [timeZone] annotation Go cannot parse
// on its own.
func parseGroupAvailabilityTime(value string) (time.Time, error) {
	var _goResult std.Try[time.Time] = func() std.Try[time.Time] {
//line group.gala:381
		var trimmed = strings.TrimSpace(value)
//line group.gala:382
		var index = std.NewImmutable(strings.LastIndex(trimmed, "["))
//line group.gala:383
		if index.Get() != -1 {
//line group.gala:384
			trimmed = string(go_interop.SliceTake(go_interop.ToBytes(trimmed), index.Get()))
		}
//line group.gala:386
		return std.GoTry(time.Parse(time.RFC3339Nano, trimmed))
	}()
	if _goResult.IsFailure() {
		return *new(time.Time), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line group.gala:388

// mergeGroupManualAvailability applies the legacy day-window replacement: an
// existing day inside a payload day's [start, start+window) span is replaced by
// the payload day, and payload days that replace nothing are appended. Deletions
// during iteration match the legacy map behavior so partially overlapping days
// resolve the same way.
func mergeGroupManualAvailability(window time.Duration, existing groupManualAvailability, incoming groupManualAvailability) groupManualAvailability {
//line group.gala:395
	var merged = groupManualAvailability{}
//line group.gala:396
	for day, times := range existing {
//line group.gala:397
		merged[day] = times
	}
//line group.gala:399
	var replacements = groupManualAvailability{}
//line group.gala:400
	for day, times := range incoming {
//line group.gala:401
		replacements[day] = times
	}
//line group.gala:403
	for day := range merged {
//line group.gala:404
		for payloadDay, availableTimes := range replacements {
//line group.gala:405
			var endTime = std.NewImmutable(payloadDay.Time().Add(window))
//line group.gala:406
			if day.Time().Compare(payloadDay.Time()) >= 0 && day.Time().Compare(endTime.Get()) <= 0 {
//line group.gala:407
				go_interop.MapDelete(merged, day)
//line group.gala:408
				merged[payloadDay] = availableTimes
//line group.gala:409
				go_interop.MapDelete(replacements, payloadDay)
//line group.gala:410
				break
			}
		}
//line group.gala:413
		if go_interop.MapLen(replacements) == 0 {
//line group.gala:414
			break
		}
	}
//line group.gala:417
	for day, times := range replacements {
//line group.gala:418
		merged[day] = times
	}
//line group.gala:420
	return merged
}

//line group.gala:422

// groupDurationHours derives the availability group's legacy duration
// from the canonical slot-generation window. The group editor defines the
// duration as the wrapped local-time window (a 09:00-17:00 group is eight
// hours), and the manual availability day-window merge spans that duration
// because the transport no longer carries the legacy duration field.
func groupDurationHours(generation *models.SlotGeneration) *float32 {
//line group.gala:429
	if generation == nil {
//line group.gala:430
		return nil
	}
//line group.gala:432
	var start, startErr = parseLocalTime(generation.StartTimeLocal)
//line group.gala:433
	if startErr != nil {
//line group.gala:434
		return nil
	}
//line group.gala:436
	var end, endErr = parseLocalTime(generation.EndTimeLocal)
//line group.gala:437
	if endErr != nil {
//line group.gala:438
		return nil
	}
//line group.gala:440
	var duration = end.Sub(start)
//line group.gala:441
	if duration <= 0 {
//line group.gala:442
		duration += 24 * time.Hour
	}
//line group.gala:444
	var hours = float32(duration.Hours())
//line group.gala:445
	return &hours
}

//line group.gala:447

// canonicalGroupResponseName resolves the guest display name for a group
// mutation, preferring the supplied name and falling back to the stored name so
// an explicit-selection edit may omit the unchanged name.
func canonicalGroupResponseName(supplied string, value *models.Response) string {
//line group.gala:452
	var name = std.NewImmutable(canonicalGuestName(supplied))
//line group.gala:453
	if name.Get() != "" {
//line group.gala:454
		return name.Get()
	}
//line group.gala:456
	if value == nil {
//line group.gala:457
		return ""
	}
//line group.gala:459
	return canonicalGuestName(value.Name)
}

//line group.gala:461

// setGroupDecline writes the attendee decline state for the respondent's
// account email. A respondent with no resolved account, or who is not an
// attendee, is left untouched. Responding clears the decline state and leaving
// sets it, matching legacy group behavior.
func setGroupDecline(ctx context.Context, tx *postgres.Repository, eventID string, stored *postgres.Response, visitor *visitor, declined bool) error {
//line group.gala:467
	var email = ""
//line group.gala:468
	if visitor != nil && visitor.platformIdentityID != "" {
//line group.gala:469
		email = accountEmail(ctx, visitor.platformIdentityID)
	}
//line group.gala:471
	if email == "" && stored != nil && stored.PlatformIdentityID != nil {
//line group.gala:472
		email = accountEmail(ctx, *stored.PlatformIdentityID)
	}
//line group.gala:474
	if email == "" {
//line group.gala:475
		return nil
	}
//line group.gala:477
	var err = tx.SetAttendeeDeclined(ctx, eventID, email, declined)
//line group.gala:478
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
//line group.gala:479
		return err
	}
//line group.gala:481
	return nil
}

//line group.gala:483

// mutateGroupResponse applies the explicit-selection contract to an
// availability group. Account respondents persist with their account identity;
// anonymous respondents persist with the shared canonical guest name. Saving a
// response clears the respondent's attendee decline state and deleting it sets
// the decline state (leaving the group). Calendar-derived mode, selected
// calendars, copied calendar preferences, and the day-window merged manual
// availability are persisted in the response payload.
func mutateGroupResponse(c *gin.Context, repository *postgres.Repository, event *postgres.Event, visitor *visitor, input responseInput, operation string) {
//line group.gala:492
	var publicID = input.ResponseID
//line group.gala:493
	var manualAvailability, decodeErr = decodeGroupManualAvailability(input.ManualAvailability)
//line group.gala:494
	if decodeErr != nil {
//line group.gala:495
		c.JSON(http.StatusBadRequest, responses.Error{Error: "invalid-manual-availability"})
//line group.gala:496
		return
	}
//line group.gala:498
	var eventValue, eventErr = eventModel(event)
//line group.gala:499
	if eventErr != nil {
//line group.gala:500
		c.JSON(http.StatusInternalServerError, responses.Error{Error: "failed-to-serialize-event"})
//line group.gala:501
		return
	}
//line group.gala:503
	var manualWindow = time.Duration(0)
//line group.gala:504
	if eventValue.Duration != nil {
//line group.gala:505
		manualWindow = time.Duration(*eventValue.Duration) * time.Hour
	}
//line group.gala:507
	var txErr = repository.WithTransaction(c.Request.Context(), func(ctx context.Context, tx *postgres.Repository) error {
//line group.gala:508
		var locked, lockErr = tx.LockEvent(ctx, event.ID)
//line group.gala:509
		if lockErr != nil {
//line group.gala:510
			return lockErr
		}
//line group.gala:512
		var writableErr = writableEvent(locked)
//line group.gala:513
		if writableErr != nil {
//line group.gala:514
			return writableErr
		}
//line group.gala:516
		var stored = &postgres.Response{EventID: event.ID, EventVisitorIdentityID: visitor.identity.ID}
//line group.gala:517
		var value *models.Response
//line group.gala:518
		if input.CreateResponse {
//line group.gala:519
			if !visitor.authorized {
//line group.gala:520
				return newGuestForbidden("visitor-credential-required")
			}
		} else {
//line group.gala:523
			var getErr error
//line group.gala:524
			stored, getErr = tx.GetResponseByPublicID(ctx, event.ID, input.ResponseID)
//line group.gala:525
			if getErr != nil {
//line group.gala:526
				return getErr
			}
//line group.gala:528
			var authorized, authErr = visitor.controls(ctx, tx, stored.EventVisitorIdentityID)
//line group.gala:529
			if authErr != nil {
//line group.gala:530
				return authErr
			}
//line group.gala:532
			if !authorized {
//line group.gala:533
				return newGuestForbidden("response-credential-required")
			}
//line group.gala:535
			var responseErr error
//line group.gala:536
			value, _, responseErr = responseModel(*stored)
//line group.gala:537
			if responseErr != nil {
//line group.gala:538
				return responseErr
			}
		}
//line group.gala:541
		if value == nil {
//line group.gala:542
			value = &models.Response{}
		}
//line group.gala:544
		if operation == "delete" {
//line group.gala:545
			var deleteErr = tx.DeleteResponse(ctx, stored.ID)
//line group.gala:546
			if deleteErr != nil {
//line group.gala:547
				return deleteErr
			}
//line group.gala:549
			var adjustErr = tx.AdjustEventResponseCount(ctx, locked.ID, -1)
//line group.gala:550
			if adjustErr != nil {
//line group.gala:551
				return adjustErr
			}
//line group.gala:553
			return setGroupDecline(ctx, tx, locked.ID, stored, visitor, true)
		}
//line group.gala:555
		if operation == "rename" {
//line group.gala:556
			var validated = std.NewImmutable(respondents.ValidateGuestName(input.NewName))
//line group.gala:557
			if validated.Get().Code != respondents.GuestNameValid {
//line group.gala:558
				return newGuestNameError(guestNameValidationErrorMessage(validated.Get().Code))
			}
//line group.gala:560
			value.Name = validated.Get().Name
		} else {
//line group.gala:562
			if input.CreateResponse {
//line group.gala:563
				if visitor.platformIdentityID != "" {
//line group.gala:564
					var platformIdentityID = visitor.platformIdentityID
//line group.gala:565
					stored.RespondentKind = postgres.RespondentKindAccount
//line group.gala:566
					stored.PlatformIdentityID = &platformIdentityID
//line group.gala:567
					value.Email = accountEmail(ctx, visitor.platformIdentityID)
				} else {
//line group.gala:569
					var guestErr = applyGroupGuestName(stored, value, input.Name)
//line group.gala:570
					if guestErr != nil {
//line group.gala:571
						return guestErr
					}
//line group.gala:573
					value.Email = input.Email
				}
			} else {
//line group.gala:576
				{
					obj := stored.RespondentKind
					if obj == postgres.RespondentKindAccount {
//line group.gala:581
						if (stored.PlatformIdentityID == nil || *stored.PlatformIdentityID == "") && visitor.platformIdentityID != "" {
//line group.gala:582
							var platformIdentityID = visitor.platformIdentityID
//line group.gala:583
							stored.PlatformIdentityID = &platformIdentityID
						}
//line group.gala:585
						if stored.PlatformIdentityID != nil && *stored.PlatformIdentityID != "" {
//line group.gala:586
							value.Email = accountEmail(ctx, *stored.PlatformIdentityID)
						}
					} else {
//line group.gala:590
						var guestErr = applyGroupGuestName(stored, value, input.Name)
//line group.gala:591
						if guestErr != nil {
//line group.gala:592
							return guestErr
						}
//line group.gala:594
						value.Email = input.Email
					}
				}
			}
//line group.gala:598
			value.Availability, value.IfNeeded = normalizeTimedResponseAvailabilitySlots(input.Availability, input.IfNeeded)
//line group.gala:599
			var existing = groupManualAvailability(nil)
//line group.gala:600
			if value.ManualAvailability != nil {
//line group.gala:601
				existing = *value.ManualAvailability
			}
//line group.gala:603
			var merged = mergeGroupManualAvailability(manualWindow, existing, manualAvailability)
//line group.gala:604
			value.ManualAvailability = &merged
//line group.gala:605
			value.UseCalendarAvailability = input.UseCalendarAvailability
//line group.gala:606
			value.EnabledCalendars = input.EnabledCalendars
//line group.gala:607
			value.CalendarOptions = input.CalendarOptions
		}
//line group.gala:609
		var payload, marshalErr = json.Marshal(value)
//line group.gala:610
		if marshalErr != nil {
//line group.gala:611
			return marshalErr
		}
//line group.gala:613
		stored.Payload = payload
//line group.gala:614
		if input.CreateResponse {
//line group.gala:615
			var createErr = tx.CreateResponse(ctx, stored)
//line group.gala:616
			if createErr != nil {
//line group.gala:617
				return createErr
			}
//line group.gala:619
			publicID = stored.PublicID
//line group.gala:620
			var countErr = tx.AdjustEventResponseCount(ctx, locked.ID, 1)
//line group.gala:621
			if countErr != nil {
//line group.gala:622
				return countErr
			}
		} else {
//line group.gala:625
			var updateErr = tx.UpdateResponse(ctx, stored)
//line group.gala:626
			if updateErr != nil {
//line group.gala:627
				return updateErr
			}
		}
//line group.gala:630
		if operation == "save" {
//line group.gala:631
			return setGroupDecline(ctx, tx, locked.ID, stored, visitor, false)
		}
//line group.gala:633
		return nil
	})
//line group.gala:635
	if txErr != nil {
//line group.gala:636
		mutationError(c, txErr)
//line group.gala:637
		return
	}
//line group.gala:639
	c.JSON(http.StatusOK, gin.H{"responseId": publicID, "eventVisitorId": visitor.identity.PublicID})
}

//line group.gala:642
func applyGroupGuestName(stored *postgres.Response, value *models.Response, supplied string) error {
//line group.gala:643
	var validated = std.NewImmutable(respondents.ValidateGuestName(canonicalGroupResponseName(supplied, value)))
//line group.gala:644
	if validated.Get().Code != respondents.GuestNameValid {
//line group.gala:645
		return newGuestNameError(guestNameValidationErrorMessage(validated.Get().Code))
	}
//line group.gala:647
	stored.RespondentKind = postgres.RespondentKindGuest
//line group.gala:648
	stored.PlatformIdentityID = nil
//line group.gala:649
	value.Name = validated.Get().Name
//line group.gala:650
	return nil
}
