// Code generated by GALA transpiler. DO NOT EDIT.

package routes

import (
	"timeful/server/models"
	"timeful/server/respondents"
)

//line guest_response_ownership.gala:8
var guestOwnershipModeToken = "token"

//line guest_response_ownership.gala:10
func hasValidGuestName(name string) bool {
	return respondents.HasValidGuestName(name)
}

//line guest_response_ownership.gala:11

// A nil response, or one owned by an account, is always exposed; a guest
// response is exposed only when it carries a valid guest name.
func shouldExposeGuestSignUpResponsePayload(_ string, response *models.SignUpResponse) bool {
	return response == nil || !response.UserId.IsZero() || hasValidGuestName(response.Name)
}
