// Code generated by GALA transpiler. DO NOT EDIT.

package routes

import (
	"timeful/server/models"
	"timeful/server/respondents"
)

//line guest_response_ownership.gala:8
var guestOwnershipModeToken = "token"

//line guest_response_ownership.gala:10
func hasValidGuestName(name string) bool {
//line guest_response_ownership.gala:11
	return respondents.HasValidGuestName(name)
}

//line guest_response_ownership.gala:14
func shouldExposeGuestSignUpResponsePayload(_ string, response *models.SignUpResponse) bool {
//line guest_response_ownership.gala:15
	if response == nil {
//line guest_response_ownership.gala:16
		return true
	}
//line guest_response_ownership.gala:19
	if !response.UserId.IsZero() {
//line guest_response_ownership.gala:20
		return true
	}
//line guest_response_ownership.gala:23
	return hasValidGuestName(response.Name)
}
