// Code generated by GALA transpiler. DO NOT EDIT.

package routes

import (
	"timeful/server/models"
	"timeful/server/respondents"
)

//line respondent_identity.gala:8
func cloneUser(user *models.User) *models.User {
//line respondent_identity.gala:9
	if user == nil {
//line respondent_identity.gala:10
		return nil
	}
//line respondent_identity.gala:13
	var clone = *user
//line respondent_identity.gala:14
	return &clone
}

//line respondent_identity.gala:17
func sanitizedResponseUser(user *models.User) *models.User {
//line respondent_identity.gala:18
	var sanitized = cloneUser(user)
//line respondent_identity.gala:19
	if sanitized == nil {
//line respondent_identity.gala:20
		return nil
	}
//line respondent_identity.gala:23
	var firstName, lastName, _ = respondents.SanitizeUserDisplayName(sanitized)
//line respondent_identity.gala:24
	sanitized.FirstName = firstName
//line respondent_identity.gala:25
	sanitized.LastName = lastName
//line respondent_identity.gala:27
	return sanitized
}

//line respondent_identity.gala:30
func canonicalGuestName(name string) string {
//line respondent_identity.gala:31
	var validation = respondents.ValidateGuestName(name)
//line respondent_identity.gala:32
	return func() string {
		if validation.Code != respondents.GuestNameValid {
			return ""
		} else {
			return validation.Name
		}
	}()
}

//line respondent_identity.gala:35
func guestNameValidationErrorMessage(code respondents.GuestNameValidationCode) string {
	return func(obj respondents.GuestNameValidationCode) string {
		if obj == respondents.GuestNameRequired {
			return "Guest name is required"
		} else if obj == respondents.GuestNameInvalidFormatting {
			return "Guest name contains only unsupported formatting characters"
		} else if obj == respondents.GuestNameAccountIDLike {
			return "Guest name cannot look like an account ID"
		} else if obj == respondents.GuestNameTooLong {
			return "Guest name must be 100 characters or fewer"
		} else {
			return "Guest name is invalid"
		}
	}(code)
}
