// Code generated by GALA transpiler. DO NOT EDIT.

package routes

import "go.gala.fyi/stdlib/std"
import (
	"go.gala.fyi/stdlib/go_interop"
	"timeful/server/models"
	"timeful/server/respondents"
)

//line respondent_identity.gala:10
func cloneUser(user *models.User) *models.User {
//line respondent_identity.gala:11
	if user == nil {
//line respondent_identity.gala:12
		return nil
	}
//line respondent_identity.gala:15
	var clone = *user
//line respondent_identity.gala:16
	return &clone
}

//line respondent_identity.gala:19
func sanitizedResponseUser(user *models.User) *models.User {
//line respondent_identity.gala:20
	var sanitized = std.NewImmutable(cloneUser(user))
//line respondent_identity.gala:21
	if sanitized.Get() == nil {
//line respondent_identity.gala:22
		return nil
	}
//line respondent_identity.gala:25
	var (
		_tmp_1, _tmp_2, _ = respondents.SanitizeUserDisplayName(sanitized.Get())
		firstName         = std.NewImmutable(_tmp_1)
		lastName          = std.NewImmutable(_tmp_2)
	)
//line respondent_identity.gala:26
	sanitized.Get().FirstName = firstName.Get()
//line respondent_identity.gala:27
	sanitized.Get().LastName = lastName.Get()
//line respondent_identity.gala:29
	return sanitized.Get()
}

//line respondent_identity.gala:32
func canonicalGuestName(name string) string {
//line respondent_identity.gala:33
	var validation = std.NewImmutable(respondents.ValidateGuestName(name))
//line respondent_identity.gala:34
	return func() string {
		if validation.Get().Code != respondents.GuestNameValid {
			return ""
		} else {
			return validation.Get().Name
		}
	}()
}

//line respondent_identity.gala:37
func guestNameValidationErrorMessage(code respondents.GuestNameValidationCode) string {
	return func(obj respondents.GuestNameValidationCode) string {
		if obj == respondents.GuestNameRequired {
			return "Guest name is required"
		} else if obj == respondents.GuestNameInvalidFormatting {
			return "Guest name contains only unsupported formatting characters"
		} else if obj == respondents.GuestNameAccountIDLike {
			return "Guest name cannot look like an account ID"
		} else if obj == respondents.GuestNameTooLong {
			return "Guest name must be 100 characters or fewer"
		} else {
			return "Guest name is invalid"
		}
	}(code)
}

//line respondent_identity.gala:44

// populateSignUpResponsePayloadIdentity resolves the response identity key and
// promotes the live account profile when one exists. liveUsers carries the
// batched account read keyed by platform identity UUID; a missing account
// (including a failed batch read) falls back to the stored response identity so
// the wire shape never gains an account shape it did not have before.
func populateSignUpResponsePayloadIdentity(response *models.SignUpResponse, liveUsers map[string]*models.User) (string, bool) {
	var _goResult std.Tuple[string, bool] = func() std.Tuple[string, bool] {
//line respondent_identity.gala:51
		if response == nil {
//line respondent_identity.gala:52
			return std.Tuple[string, bool]{V1: std.NewImmutable(""), V2: std.NewImmutable(false)}
		}
//line respondent_identity.gala:55
		if !response.UserId.IsZero() {
//line respondent_identity.gala:56
			var lookupKey = std.NewImmutable(response.UserId.String())
//line respondent_identity.gala:57
			func(obj std.Option[*models.User]) {
				{
					_tmp_3 := std.Some[*models.User]{}.Unapply(obj)
					_tmp_4 := _tmp_3.IsDefined()
					var _tmp_5 *models.User
					if _tmp_4 {
						_tmp_5 = _tmp_3.Get()
					}
					_ = _tmp_5
					liveUser := _tmp_5
					if _tmp_4 && liveUser != nil {
						response.User = sanitizedResponseUser(liveUser)
					} else {
//line respondent_identity.gala:60
						var fallbackName = std.NewImmutable(respondents.NormalizeGuestName(response.Name))
//line respondent_identity.gala:61
						response.User = &models.User{Id: response.UserId, FirstName: fallbackName.Get(), Email: response.Email}
					}
				}
			}(go_interop.OptionFromMap(liveUsers, lookupKey.Get()))
//line respondent_identity.gala:68
			return std.Tuple[string, bool]{V1: std.NewImmutable(lookupKey.Get()), V2: std.NewImmutable(true)}
		}
//line respondent_identity.gala:71
		var name = std.NewImmutable(canonicalGuestName(response.Name))
//line respondent_identity.gala:72
		if name.Get() == "" {
//line respondent_identity.gala:73
			return std.Tuple[string, bool]{V1: std.NewImmutable(""), V2: std.NewImmutable(false)}
		}
//line respondent_identity.gala:76
		response.Name = name.Get()
//line respondent_identity.gala:77
		response.User = &models.User{FirstName: name.Get(), Email: response.Email}
//line respondent_identity.gala:81
		return std.Tuple[string, bool]{V1: std.NewImmutable(name.Get()), V2: std.NewImmutable(true)}
	}()
	return _goResult.V1.Get(), _goResult.V2.Get()
}
