// Code generated by GALA transpiler. DO NOT EDIT.

package routes

import "go.gala.fyi/stdlib/std"
import (
	"github.com/gin-gonic/gin"
	"net/http"
	"timeful/server/accounts"
	"timeful/server/errs"
	"timeful/server/models"
	"timeful/server/responses"
)

//line users.gala:13
func InitUsers(router *gin.RouterGroup) {
//line users.gala:14
	var usersRouter = std.NewImmutable(router.Group("/users"))
//line users.gala:18
	usersRouter.Get().GET("/:userId", getPublicUserProfile)
}

//line users.gala:20

// @Summary Returns a minimal public user profile (safe for unauthenticated clients)
// @Tags users
// @Produce json
// @Param userId path string true "User ID"
// @Success 200 {object} models.User
// @Router /users/{userId} [get]
func getPublicUserProfile(c *gin.Context) {
//line users.gala:28
	var platformIdentityID = std.NewImmutable(c.Param("userId"))
//line users.gala:29
	var user = std.NewImmutable(accounts.UserByPlatformIdentityID(platformIdentityID.Get()))
//line users.gala:30
	if user.Get() == nil {
//line users.gala:31
		c.JSON(http.StatusNotFound, responses.Error{Error: errs.UserDoesNotExist})
//line users.gala:32
		return
	}
//line users.gala:35
	var public = std.NewImmutable(models.User{Id: user.Get().Id, FirstName: user.Get().FirstName, LastName: user.Get().LastName, Picture: user.Get().Picture})
//line users.gala:41
	c.JSON(http.StatusOK, public.Get())
}
