// Code generated by GALA transpiler. DO NOT EDIT.

package postgres

import "go.gala.fyi/stdlib/std"
import (
	"bytes"
	"encoding/json"
	"fmt"
)
import "go.gala.fyi/stdlib/go_interop"

//line codec.gala:11
var emptyPayload = json.RawMessage(go_interop.ToBytes("{}"))

//line codec.gala:13
func encodePayload(payload json.RawMessage) ([]byte, error) {
	var _goResult std.Try[[]byte] = func() std.Try[[]byte] {
//line codec.gala:14
		if len(payload) == 0 {
//line codec.gala:15
			return std.Success[[]byte]{}.Apply(go_interop.SliceCopy(emptyPayload))
		}
//line codec.gala:17
		if !json.Valid(payload) {
//line codec.gala:18
			return std.Failure[[]byte]{}.Apply(fmt.Errorf("payload is not valid JSON"))
		}
//line codec.gala:20
		if !bytes.HasPrefix(bytes.TrimSpace(payload), go_interop.ToBytes("{")) {
//line codec.gala:21
			return std.Failure[[]byte]{}.Apply(fmt.Errorf("payload must be a JSON object"))
		}
//line codec.gala:23
		var value map[string]json.RawMessage
//line codec.gala:24
		var unmarshalErr = json.Unmarshal(payload, &value)
//line codec.gala:25
		if unmarshalErr != nil {
//line codec.gala:26
			return std.Failure[[]byte]{}.Apply(fmt.Errorf("payload must be a JSON object: %w", unmarshalErr))
		}
//line codec.gala:28
		return std.Success[[]byte]{}.Apply(go_interop.SliceCopy(payload))
	}()
	if _goResult.IsFailure() {
		return *new([]byte), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line codec.gala:31
func decodePayload(payload []byte) json.RawMessage {
//line codec.gala:32
	if len(payload) == 0 {
//line codec.gala:33
		var empty json.RawMessage
//line codec.gala:34
		return empty
	}
//line codec.gala:36
	return json.RawMessage(go_interop.SliceCopy(payload))
}
