// Code generated by GALA transpiler. DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"fmt"
	"github.com/jackc/pgx/v5/pgxpool"
	"go.opentelemetry.io/otel/trace"
	"os"
	"strconv"
	"time"
)
import "go.gala.fyi/stdlib/resource"

//line pool.gala:17
var applicationURIEnvironment = "POSTGRES_APPLICATION_URI"

//line pool.gala:19
var connectTimeoutEnvironment = "POSTGRES_CONNECT_TIMEOUT_SECONDS"

//line pool.gala:21
var maxConnectionsEnvironment = "POSTGRES_MAX_CONNS"

//line pool.gala:23
var Pool *pgxpool.Pool

//line pool.gala:24

// Init connects and verifies the PostgreSQL store before the server accepts
// requests, and installs the query tracer so database work joins its request
// trace. PostgreSQL-owned event routes may be enabled after startup.
func Init(tracerProvider trace.TracerProvider) func() {
//line pool.gala:29
	var uri = os.Getenv(applicationURIEnvironment)
//line pool.gala:30
	if uri == "" {
//line pool.gala:31
		panic(applicationURIEnvironment + " environment variable is required")
	}
//line pool.gala:34
	var config, parseErr = pgxpool.ParseConfig(uri)
//line pool.gala:35
	if parseErr != nil {
//line pool.gala:36
		panic(fmt.Sprintf("invalid %s: %v", applicationURIEnvironment, parseErr))
	}
//line pool.gala:38
	config.MaxConns = environmentInt(maxConnectionsEnvironment, 10)
//line pool.gala:39
	config.ConnConfig.Tracer = newQueryTracer(tracerProvider)
//line pool.gala:41
	var ctx, cancel = context.WithTimeout(context.Background(), connectionTimeout())
//line pool.gala:42
	var closeFn func() = resource.Bracket(cancel, func(c context.CancelFunc) {
		c()
	}, func(_ context.CancelFunc) func() {
//line pool.gala:43
		var createdPool, connErr = pgxpool.NewWithConfig(ctx, config)
//line pool.gala:44
		Pool = createdPool
//line pool.gala:45
		if connErr != nil {
//line pool.gala:46
			panic(fmt.Sprintf("connect to PostgreSQL: %v", connErr))
		}
//line pool.gala:48
		var pingErr = Pool.Ping(ctx)
//line pool.gala:49
		if pingErr != nil {
//line pool.gala:50
			Pool.Close()
//line pool.gala:51
			Pool = nil
//line pool.gala:52
			panic(fmt.Sprintf("ping PostgreSQL: %v", pingErr))
		}
//line pool.gala:54
		return func() {
//line pool.gala:55
			if Pool != nil {
//line pool.gala:56
				Pool.Close()
//line pool.gala:57
				Pool = nil
			}
		}
	})
//line pool.gala:61
	return closeFn
}

//line pool.gala:64
func Ping(ctx context.Context) error {
//line pool.gala:65
	if Pool == nil {
//line pool.gala:66
		return errors.New("postgresql pool is not initialized")
	}
//line pool.gala:68
	return Pool.Ping(ctx)
}

//line pool.gala:71
func connectionTimeout() time.Duration {
	return time.Duration(environmentInt(connectTimeoutEnvironment, 10)) * time.Second
}

//line pool.gala:73
func environmentInt(name string, fallback int) int32 {
//line pool.gala:74
	var value = os.Getenv(name)
//line pool.gala:75
	if value == "" {
//line pool.gala:76
		return int32(fallback)
	}
//line pool.gala:78
	var parsed, parseErr = strconv.ParseInt(value, 10, 32)
//line pool.gala:79
	if parseErr != nil || parsed < 1 {
//line pool.gala:80
		panic(fmt.Sprintf("%s must be a positive integer", name))
	}
//line pool.gala:82
	return int32(parsed)
}
