// Code generated by GALA transpiler. DO NOT EDIT.

package postgres

import "go.gala.fyi/stdlib/std"
import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)
import "go.gala.fyi/stdlib/go_interop"

//line repository.gala:22
var crockfordBase32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

//line repository.gala:24
var ErrPoolUninitialized = errors.New("postgresql pool is not initialized")

//line repository.gala:25

// rowScanner names the anonymous `interface{ Scan(...any) error }` parameter
// that scanEvent took from the Go original, because GALA has no syntax for an
// anonymous interface type.
type rowScanner interface {
	Scan(dest ...any) error
}

//line repository.gala:33
func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{db: pool}
}

//line repository.gala:34

// NewRepositoryFromTx binds a repository to an existing transaction so a caller
// that owns the transaction can compose repository operations with its own SQL
// in one atomic unit of work.
func NewRepositoryFromTx(tx pgx.Tx) *Repository {
	return &Repository{db: tx}
}

//line repository.gala:39

// DefaultRepository uses the package-global pool initialized by Init.
func DefaultRepository() (*Repository, error) {
	var _goResult std.Try[*Repository] = func() std.Try[*Repository] {
//line repository.gala:42
		if Pool == nil {
//line repository.gala:43
			return std.Failure[*Repository]{}.Apply(ErrPoolUninitialized)
		}
//line repository.gala:45
		return std.Success[*Repository]{}.Apply(NewRepository(Pool))
	}()
	if _goResult.IsFailure() {
		return *new(*Repository), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line repository.gala:47

// WithTransaction runs fn against the package-global pool in one transaction.
func WithTransaction(ctx context.Context, fn func(context.Context, *Repository) error) error {
//line repository.gala:50
	var repository, repoErr = DefaultRepository()
//line repository.gala:51
	if repoErr != nil {
//line repository.gala:52
		return repoErr
	}
//line repository.gala:54
	return repository.WithTransaction(ctx, fn)
}

//line repository.gala:57
func GenerateShortID() (string, error) {
	var _goResult std.Try[string] = func() std.Try[string] {
//line repository.gala:58
		var value = go_interop.SliceWithSize[byte](5)
//line repository.gala:59
		var _, readErr = rand.Read(value)
//line repository.gala:60
		if readErr != nil {
//line repository.gala:61
			return std.Failure[string]{}.Apply(fmt.Errorf("generate short event ID: %w", readErr))
		}
//line repository.gala:63
		return std.Success[string]{}.Apply(encodeCrockford(value, 8))
	}()
	if _goResult.IsFailure() {
		return *new(string), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line repository.gala:66
func GenerateEventShortID() (string, error) {
	return GenerateShortID()
}

//line repository.gala:67

// GenerateTransferCode returns a six-digit decimal matching code. Rejection
// sampling keeps the value uniform without modulo bias, and formatting keeps
// leading zeros so every code is exactly six digits.
func GenerateTransferCode() (string, error) {
	var _goResult std.Try[string] = func() std.Try[string] {
//line repository.gala:72
		var raw = go_interop.SliceWithSize[byte](4)
//line repository.gala:73
		for {
//line repository.gala:74
			var _, readErr = rand.Read(raw)
//line repository.gala:75
			if readErr != nil {
//line repository.gala:76
				return std.Failure[string]{}.Apply(fmt.Errorf("generate transfer code: %w", readErr))
			}
//line repository.gala:78
			var value = uint32(raw[0])<<24 | uint32(raw[1])<<16 | uint32(raw[2])<<8 | uint32(raw[3])
//line repository.gala:79
			if value >= 4000000000 {
//line repository.gala:80
				continue
			}
//line repository.gala:82
			return std.Success[string]{}.Apply(formatTransferCode(value % 1000000))
		}
	}()
	if _goResult.IsFailure() {
		return *new(string), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line repository.gala:86
func formatTransferCode(value uint32) string {
	return fmt.Sprintf("%06d", value)
}

//line repository.gala:88
func encodeCrockford(value []byte, length int) string {
//line repository.gala:89
	var result = go_interop.SliceWithSize[byte](length)
//line repository.gala:90
	var buffer uint64
//line repository.gala:91
	var bits = uint(0)
//line repository.gala:92
	var index = 0
//line repository.gala:93
	for _, b := range value {
//line repository.gala:94
		buffer = buffer<<8 | uint64(b)
//line repository.gala:95
		bits += 8
//line repository.gala:96
		for bits >= 5 && index < length {
//line repository.gala:97
			bits -= 5
//line repository.gala:98
			result[index] = crockfordBase32[(buffer>>bits)&31]
//line repository.gala:99
			index++
		}
	}
//line repository.gala:102
	if index < length && bits > 0 {
//line repository.gala:103
		result[index] = crockfordBase32[(buffer<<(5-bits))&31]
	}
//line repository.gala:105
	return string(result)
}

//line repository.gala:108
var eventColumns = `id, short_id, owner_edit_token_hash, owner_platform_identity_id, owner_event_visitor_identity_id, name, type, is_archived, is_deleted, num_responses, schedule_version, creator_posthog_id, created_at, updated_at, payload`

//line repository.gala:110
func scanEvent(row rowScanner) (*Event, error) {
	var _goResult std.Try[*Event] = func() std.Try[*Event] {
//line repository.gala:111
		var event = &Event{}
//line repository.gala:112
		var scanErr = row.Scan(&event.ID, &event.ShortID, &event.OwnerEditTokenHash, &event.OwnerPlatformIdentityID, &event.OwnerEventVisitorIdentityID, &event.Name, &event.Type, &event.IsArchived, &event.IsDeleted, &event.NumResponses, &event.ScheduleVersion, &event.CreatorPosthogID, &event.CreatedAt, &event.UpdatedAt, &event.Payload)
//line repository.gala:113
		if scanErr != nil {
//line repository.gala:114
			return std.Failure[*Event]{}.Apply(scanErr)
		}
//line repository.gala:116
		event.Payload = decodePayload(event.Payload)
//line repository.gala:117
		return std.Success[*Event]{}.Apply(event)
	}()
	if _goResult.IsFailure() {
		return *new(*Event), _goResult.GetError()
	}
	return _goResult.Get(), nil
}

//line repository.gala:119

// listResponsesQuery lists one event's responses in write order. The
// supporting-index forced-plan test runs this statement directly.
var listResponsesQuery = `SELECT id, public_id, event_visitor_identity_id, event_id, respondent_kind, platform_identity_id, payload, created_at, updated_at FROM event_responses WHERE event_id = $1 ORDER BY created_at, id`

//line repository.gala:124
func isUniqueViolation(err error) bool {
//line repository.gala:125
	var postgresError *pgconn.PgError
//line repository.gala:126
	return errors.As(err, &postgresError) && postgresError.Code == "23505"
}

//line repository.gala:128

// IsUniqueViolation reports PostgreSQL unique-index conflicts to route adapters.
func IsUniqueViolation(err error) bool {
	return isUniqueViolation(err)
}
