// Code generated by GALA transpiler. DO NOT EDIT.

package errs

//line errors.gala:3
var EventOwnerCredentialRequired = "event-owner-credential-required"

//line errors.gala:4
var EventArchived = "event-archived"

//line errors.gala:5

// Errors enum
// TODO: make these an actual type (i.e. Errors.NotSignedIn)
var NotSignedIn string = "not-signed-in"

//line errors.gala:9
var UserDoesNotExist string = "user-does-not-exist"

//line errors.gala:10
var AccountEmailMismatch string = "account-email-mismatch"

//line errors.gala:11
var EventNotFound string = "event-not-found"

//line errors.gala:12
var EventNameTooLong string = "event-name-too-long"

//line errors.gala:13
var UserNotEventOwner string = "user-not-event-owner"

//line errors.gala:14
var AttendeeEmailNotFound string = "attendee-email-not-found"

//line errors.gala:15
var EventNotGroup string = "event-not-group"

//line errors.gala:16
var InvalidCredentials string = "invalid-credentials"

//line errors.gala:17
var OtpExpired string = "otp-expired"

//line errors.gala:18
var OtpInvalidCode string = "otp-invalid-code"

//line errors.gala:19
var OtpTooManyAttempts string = "otp-too-many-attempts"

//line errors.gala:20
var InvalidIdToken string = "invalid-id-token"
