// Code generated by GALA transpiler. DO NOT EDIT.

// Package eventid validates canonical public event identifiers.
//
// The canonical form is an eight-character Crockford base32 identifier.
// The package source lives in eventid.gala; eventid.go is its transpiled output.
package eventid

import "go.gala.fyi/stdlib/std"
import "regexp"

//line eventid.gala:8

// canonicalShortID matches an eight-character Crockford base32 identifier.
var canonicalShortID = std.NewImmutable(regexp.MustCompile(`^[0-9A-HJKMNPQRSTVWXYZ]{8}$`))

//line eventid.gala:11

// Canonical reports whether id is an eight-character Crockford base32 event
// identifier.
// id: the identifier to test.
func Canonical(id string) bool {
	return canonicalShortID.Get().MatchString(id)
}
