// Code generated by GALA transpiler. DO NOT EDIT.

package eventid

import "regexp"

//line eventid.gala:9
var canonicalShortID = regexp.MustCompile(`^[0-9A-HJKMNPQRSTVWXYZ]{8}$`)

//line eventid.gala:14
func Canonical(id string) bool {
	return canonicalShortID.MatchString(id)
}
