// Code generated by GALA transpiler. DO NOT EDIT.

package models

import "go.gala.fyi/stdlib/std"
import "time"

//line datetime.gala:4

// DateTime is a canonical millisecond-precision instant. Its JSON representation
// is an RFC3339 string for values and a millisecond integer when used as a map
// key.
type DateTime int64

func (s DateTime) Hash() uint32 {
	return std.HashInt(int64(s))
}
func (s DateTime) Compare(other DateTime) int {
	return std.CompareInt(int64(s), int64(other))
}

//line datetime.gala:9

// Time returns the instant.
func (d DateTime) Time() time.Time {
	return time.UnixMilli(int64(d))
}

//line datetime.gala:12

// IsZero reports whether the value is the Unix epoch default.
func (d DateTime) IsZero() bool {
	return d == 0
}

//line datetime.gala:15

// NewDateTimeFromTime converts a time into millisecond precision.
func NewDateTimeFromTime(value time.Time) DateTime {
	return DateTime(value.UnixMilli())
}
