// Code generated by GALA transpiler. DO NOT EDIT.

package models

import "go.gala.fyi/stdlib/std"

//line uuid.gala:2

// ZeroUUID returns the all-zero UUID sentinel the API emits for a zero account
// identity. It is surfaced to clients for an absent account identity (for
// example the guest userId) and for unowned events, so the wire format must
// keep it. It is exposed as a function so callers cannot overwrite the
// sentinel.
func ZeroUUID() UUID {
	return zeroUUIDValue
}

//line uuid.gala:9

// UUID is a canonical lowercase hyphenated RFC 9562 UUID string. Its JSON
// representation is that canonical form, and its empty value serializes as the
// all-zero sentinel. The zero UUID represents an absent account identity and is
// never a stored account.
type UUID string

func (s UUID) Hash() uint32 {
	return std.HashString(string(s))
}
func (s UUID) Compare(other UUID) int {
	return std.CompareString(string(s), string(other))
}

//line uuid.gala:15

// String returns the canonical lowercase hyphenated form, mapping the empty
// value to the all-zero sentinel.
func (id UUID) String() string {
//line uuid.gala:19
	if id == "" {
//line uuid.gala:20
		return zeroUUIDValue
	}
//line uuid.gala:22
	return string(id)
}

//line uuid.gala:24

// IsZero reports whether the identifier is the empty or all-zero sentinel
// value.
func (id UUID) IsZero() bool {
	return id == "" || id == zeroUUIDValue
}
