// Code generated by GALA transpiler. DO NOT EDIT.

package commands

import (
	"fmt"
	"github.com/bwmarrin/discordgo"
)

//line help.gala:9
func executeHelp(s *discordgo.Session, m *discordgo.MessageCreate, args []string) {
//line help.gala:10
	var message string
//line help.gala:11
	for _, command := range Commands {
//line help.gala:12
		message += fmt.Sprintf("\n\n`%s`: %s ", command.Name, command.Description)
//line help.gala:13
		if command.Usage != "" {
//line help.gala:14
			message += fmt.Sprintf("Usage: `%s`", command.Usage)
		}
	}
//line help.gala:18
	sendMessage(s, m, message)
}

//line help.gala:21
var help Command = Command{Name: "!help", Description: "Displays this help message", Execute: executeHelp}
