// Code generated by GALA transpiler. DO NOT EDIT.

package commands

import "fmt"
import "github.com/bwmarrin/discordgo"

//line help.gala:5
func executeHelp(s *discordgo.Session, m *discordgo.MessageCreate, args []string) {
//line help.gala:6
	var message string
//line help.gala:7
	for _, command := range Commands {
//line help.gala:8
		message += fmt.Sprintf("\n\n`%v`: %v ", command.Name, command.Description)
//line help.gala:9
		if command.Usage != "" {
//line help.gala:10
			message += fmt.Sprintf("Usage: `%v`", command.Usage)
		}
	}
//line help.gala:14
	sendMessage(s, m, message)
}

//line help.gala:17
var help Command = Command{Name: "!help", Description: "Displays this help message", Execute: executeHelp}
