// Code generated by GALA transpiler. DO NOT EDIT.

package commands

import "fmt"
import (
	"context"
	"github.com/bwmarrin/discordgo"
	"timeful/server/logger"
	pgstore "timeful/server/postgres"
)

//line num_users.gala:11
func executeNumUsers(s *discordgo.Session, m *discordgo.MessageCreate, args []string) {
//line num_users.gala:12
	var repository, err = pgstore.DefaultRepository()
//line num_users.gala:13
	if err != nil {
//line num_users.gala:14
		logger.StdErr.Panicln(err)
	}
//line num_users.gala:16
	var n, countErr = repository.CountAccounts(context.Background())
//line num_users.gala:17
	if countErr != nil {
//line num_users.gala:18
		logger.StdErr.Panicln(countErr)
	}
//line num_users.gala:21
	sendMessage(s, m, fmt.Sprintf("Number of currently signed up users: %v", n))
}

//line num_users.gala:24
var numUsers Command = Command{Name: "!num_users", Description: "Returns the number of signed up users", Execute: executeNumUsers}
