// Code generated by GALA transpiler. DO NOT EDIT.

package services

import "fmt"
import "go.gala.fyi/stdlib/std"
import (
	"bytes"
	"encoding/json"
	"net/http"
	"timeful/server/logger"
	"timeful/server/models"
	"timeful/server/services/auth"
)

//line services.gala:13
func CallApi(user *models.User, calendarAuth *models.OAuth2CalendarAuth, method string, url string, body *map[string]any) *http.Response {
//line services.gala:14
	if user != nil {
//line services.gala:15
		auth.RefreshUserTokenIfNecessary(user, nil)
	}
//line services.gala:20
	var req *http.Request
//line services.gala:21
	if body != nil {
//line services.gala:22
		var (
			_tmp_1, _ = json.Marshal(body)
			bodyBytes = std.NewImmutable(_tmp_1)
		)
//line services.gala:23
		var (
			_tmp_2, _ = http.NewRequest(method, url, bytes.NewBuffer(bodyBytes.Get()))
			created   = std.NewImmutable(_tmp_2)
		)
//line services.gala:24
		req = created.Get()
	} else {
//line services.gala:26
		var (
			_tmp_3, _ = http.NewRequest(method, url, nil)
			created   = std.NewImmutable(_tmp_3)
		)
//line services.gala:27
		req = created.Get()
	}
//line services.gala:29
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", calendarAuth.AccessToken))
//line services.gala:31
	var response = std.NewImmutable(std.GoTry(http.DefaultClient.Do(req)).OnFailure(func(err error) {
		logger.StdErr.Panicln(err)
	}).Get())
//line services.gala:33
	return response.Get()
}
