// Code generated by GALA transpiler. DO NOT EDIT.

package middleware

import "martianoff/gala/std"
import (
	"github.com/gin-contrib/sessions"
	"github.com/gin-gonic/gin"
	"net/http"
	"timeful/server/accounts"
	"timeful/server/errs"
	"timeful/server/responses"
)

//line auth.gala:29
func AuthRequired() gin.HandlerFunc {
	return func(c *gin.Context) {
//line auth.gala:30
		var platformIdentityID = func(obj any) string {
			{
				s, _tmp_1 := std.As[string](obj)
				if _tmp_1 {
					return s
				} else {
					return ""
				}
			}
		}(sessions.Default(c).Get("userId"))
//line auth.gala:34
		if platformIdentityID == "" {
//line auth.gala:35
			c.JSON(http.StatusUnauthorized, responses.Error{Error: errs.NotSignedIn})
//line auth.gala:36
			c.Abort()
//line auth.gala:37
			return
		}
//line auth.gala:40
		var account, err = accounts.Resolve(c.Request.Context(), platformIdentityID)
//line auth.gala:41
		if err != nil {
//line auth.gala:42
			c.JSON(http.StatusUnauthorized, responses.Error{Error: errs.UserDoesNotExist})
//line auth.gala:43
			c.Abort()
//line auth.gala:44
			return
		}
//line auth.gala:47
		var user, loadErr = accounts.LoadSessionUser(c.Request.Context(), account)
//line auth.gala:48
		if loadErr != nil {
//line auth.gala:49
			c.JSON(http.StatusInternalServerError, responses.Error{Error: "failed to load account integration data"})
//line auth.gala:50
			c.Abort()
//line auth.gala:51
			return
		}
//line auth.gala:54
		c.Set("authUser", user)
//line auth.gala:55
		c.Set("authAccount", account)
//line auth.gala:56
		c.Next()
	}
}
