// Code generated by GALA transpiler. DO NOT EDIT.

package middleware

import (
	"github.com/gin-gonic/gin"
	"net/http"
	"timeful/server/accounts"
	"timeful/server/errs"
	"timeful/server/responses"
)

//line auth.gala:11

// AuthRequired rejects a request that carries no usable session identity.
//
// The session carries the account's platform identity UUID. A session value
// that is absent, is not a string, or is the empty string is treated the same
// way, because only a non-empty platform identity can be resolved.
//
// The authoritative account is then resolved from PostgreSQL, and the calendar
// connections, provider tokens, sub-calendars, and preferences are
// PostgreSQL-authoritative and loaded through the accounts boundary rather
// than from the session.
//
// On success the resolved user and account are published on the Gin context as
// "authUser" and "authAccount" and the handler chain continues.
//
// This documentation lives here rather than in doc.go so it stays with the
// declaration it documents.
func AuthRequired() gin.HandlerFunc {
	return func(c *gin.Context) {
//line auth.gala:29
		var platformIdentityID = sessionIdentityID(c)
//line auth.gala:30
		if platformIdentityID == "" {
//line auth.gala:31
			c.JSON(http.StatusUnauthorized, responses.Error{Error: errs.NotSignedIn})
//line auth.gala:32
			c.Abort()
//line auth.gala:33
			return
		}
//line auth.gala:36
		var account, err = accounts.Resolve(c.Request.Context(), platformIdentityID)
//line auth.gala:37
		if err != nil {
//line auth.gala:38
			c.JSON(http.StatusUnauthorized, responses.Error{Error: errs.UserDoesNotExist})
//line auth.gala:39
			c.Abort()
//line auth.gala:40
			return
		}
//line auth.gala:43
		var user, loadErr = accounts.LoadSessionUser(c.Request.Context(), account)
//line auth.gala:44
		if loadErr != nil {
//line auth.gala:45
			c.JSON(http.StatusInternalServerError, responses.Error{Error: "failed to load account integration data"})
//line auth.gala:46
			c.Abort()
//line auth.gala:47
			return
		}
//line auth.gala:50
		c.Set("authUser", user)
//line auth.gala:51
		c.Set("authAccount", account)
//line auth.gala:52
		c.Next()
	}
}
