// Code generated by GALA transpiler. DO NOT EDIT.

package utils

//line array_utils.gala:3
func Find[T any](arr []T, equals func(T) bool) int {
//line array_utils.gala:4
	for i, v := range arr {
//line array_utils.gala:5
		if equals(v) {
//line array_utils.gala:6
			return i
		}
	}
//line array_utils.gala:9
	return -1
}
