// Code generated by GALA transpiler. DO NOT EDIT.

package utils

import "go.gala.fyi/stdlib/std"
import (
	"github.com/gin-gonic/gin"
	"net/url"
	"strings"
	"timeful/server/logger"
)

//line request_utils.gala:11
func ParseArrayQueryParam(s string) []string {
//line request_utils.gala:12
	var decoded = std.NewImmutable(std.GoTry(url.QueryUnescape(s)).OnFailure(func(err error) {
		logger.StdErr.Panicln(err)
	}).Get())
//line request_utils.gala:13
	var arr = std.NewImmutable(strings.Split(decoded.Get(), ","))
//line request_utils.gala:14
	return arr.Get()
}

//line request_utils.gala:17
func GetOrigin(c *gin.Context) string {
	return c.Request.Header.Get("Origin")
}
