// Code generated by GALA transpiler. DO NOT EDIT.

package utils

import (
	"github.com/gin-gonic/gin"
	"net/url"
	"strings"
	"timeful/server/logger"
)

//line request_utils.gala:11
func ParseArrayQueryParam(s string) []string {
//line request_utils.gala:12
	var decoded, err = url.QueryUnescape(s)
//line request_utils.gala:13
	if err != nil {
//line request_utils.gala:14
		logger.StdErr.Panicln(err)
	}
//line request_utils.gala:16
	var arr = strings.Split(decoded, ",")
//line request_utils.gala:17
	return arr
}

//line request_utils.gala:20
func GetOrigin(c *gin.Context) string {
//line request_utils.gala:21
	return c.Request.Header.Get("Origin")
}
